### ISSUE TITLE
Message `Invoking ...` breaks command substitution and pipelining

### ISSUE THREAD

**Issue by suhlig** [IBM-Cloud/ibm-cloud-cli-release#101]
# Observed Behaviour

The `ibmcloud` tool adds a line like `Invoking 'cf ...'` to **stdout** of the invoked command:

```command
$ ibmcloud cf curl /v2/info
Invoking 'cf curl /v2/info'...

{
  "name": "IBM Cloud",
  "build": "6.8.0",
   ...
```

# The Problem

This breaks many use cases where the output is being used in shell substitutions or pipelines, for instance for grabbing a specific value from the command above using `jq`:

```command
$ ibmcloud cf curl /v2/info | jq -r .app_ssh_endpoint
parse error: Invalid numeric literal at line 1, column 9
```

Doing the same with the plain `cf` command works fine, because it does provide valid JSON:

```command
$ cf curl /v2/info | jq -r .app_ssh_endpoint
ssh.eu-de.cf.cloud.ibm.com:2222
```

# Suggested Solution

I would like to suggest to write this line to **stderr** instead, or providing an option to suppress this line.

# Workaround

Suppressing the offending line with an additional `grep` helps, but it is annoying and should not be necessary:

```command
$ ibmcloud cf curl /v2/info | grep -v '^Invoking' | jq -r .app_ssh_endpoint
ssh.eu-de.cf.cloud.ibm.com:2222
```

# Meta

```command
$ ibmcloud --version
ibmcloud version 0.18.1+09d36ed-2019-08-19T09:04:14+00:00
```

**Comment by suhlig** [comment]
I just found that there is `--quiet`, which does what I want:

```command
$ ibmcloud --quiet cf curl /v2/info | jq -r .app_ssh_endpoint
```

Why is this global option not documented?

**Comment by steveclay** [comment]
`cf` is actually a separate CLI that is not developed by this team, but can be invoked by the IBM Cloud CLI.
