### ISSUE TITLE
No support for ARM architecture

### ISSUE THREAD

**Issue by epicnational** [IBM-Cloud/ibm-cloud-cli-release#103]
Will support for ARM be added in the future? With IBM's push towards the cloud and IoT, it is really frustrating this is still not supported.

**Comment by sbason** [comment]
This would be really great. I opened this Issue a few years ago but I did not get a positive response: https://github.com/IBM-Cloud/ibm-cloud-cli-release/issues/7

**Comment by dnalexxio** [comment]
looking forward for this feature

**Comment by giminni** [comment]
I am currently implementing AI services on nVIDIA nano with IBM Edge Application Manager, it will be very helpful if I can use ibmcloud to store the docker container in IBM Container Registry.

**Comment by appcypher** [comment]
It is more important now to have ARM options looking at how well M1 is doing.
I think it is inevitable.

**Comment by rofrano** [comment]
ARM support is desperately needed. Developers are buying **Apple M1 Silicon Macs** because they are screaming fast with all day battery life and while the IBM Cloud CLI does work with Rosetta 2 emulation on macOS, many developers are developing in virtual machines and Docker containers which are all arch64 linux on the M1 Mac and the `ibmcloud` CLI does not work. 

We really need native support for ARM now more than ever. Apple M1 is the future. It's only going to get worse.

**Comment by Syleron** [comment]
+1 Not having arm support is a massive let down...

**Comment by lra** [comment]
This is now needed for all of us using an Apple M1.

**Comment by dotnsf** [comment]
That would be nice for Raspberry Pi users too.

**Comment by steveclay** [comment]
We have added as-is versions for ARM now. Please see https://github.com/IBM-Cloud/ibm-cloud-cli-release/releases/tag/v2.6.0 for more the latest available.

**Comment by rofrano** [comment]
@steveclay  Congratulation on acknowledging the ARM community but... I still get the following error:

```bash
$ curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
Unsupported Linux architecture: aarch64. Quit installation.
```

I expect the ARM version to be installed.

**Comment by dotnsf** [comment]
I have downloaded and installed **Linux 64 bit ARM binary** on my **Raspberry Pi OS(64bit)**. And I have confirmed it worked! Thanks!!

![image](https://user-images.githubusercontent.com/3183150/162118390-b924ac49-18f1-483c-935e-1c0823ac5b97.png)

**Comment by rofrano** [comment]
@dotnsf Did you have to modify the `install` script? There is no way to get it installed unless you modify the `install` script or copy the files manually. Then it works, but it doesn't even install to begin with. 

I added `aarch64` as a `case` statement in the install script like this:

```bash
MARCH=$(uname -m | tr '[:upper:]' '[:lower:]')
case "$MARCH" in
"aarch64") ;;
"ppc64le") ;;
"x86_64") ;;
"x86_32") ;;
"s390x") ;;
*)
```

and then it worked, but I shouldn't have to do that.

**Comment by dotnsf** [comment]
@rofrano I didn't use installer version of this. I had just downloaded and expanded from tgz **binary** of "Linux 64 bit ARM (as-is)". It worked in my Raspberry Pi OS.
