### ISSUE TITLE
Error messages when quota for container registry exceeded

### ISSUE THREAD

**Issue by danielgorgis96** [IBM-Cloud/ibm-cloud-cli-release#105]
When using the container registry with kubernetes the error message displayed when the quota for the registry has been exceeded says: 403 forbidden. And when interacting with the ibmcloud cr, there's no information about the quota being exceeded, unless you specifically run the quota command. Wouldn't it be better to let the user know, that the quota is exceeded upon login ?

**Comment by steveclay** [comment]
Thank you for this suggestion. I will forward to this team.
