### ISSUE TITLE
ibmcloud resource service-instance-create  multiple instances with same name

### ISSUE THREAD

**Issue by dkolitha** [IBM-Cloud/ibm-cloud-cli-release#107]
ibmcloud resource service-instance-create event-stream-01 messagehub standard us-south

Execute the command multiple times and it creates service instances with same name.

**Comment by shemau** [comment]
ibmcloud resource service-key-create has the same issue. Multiple keys with the same name.

**Comment by steveclay** [comment]
I believe this is working as designed as the name does not have to be unique, but the ID for each instance will be unique.
