### ISSUE TITLE
New version of cli removes --export

### ISSUE THREAD

**Issue by braddison** [IBM-Cloud/ibm-cloud-cli-release#108]
Hello, 

The new version seems to be missing the ability to --export the kubernetes config to your shell. Not only does this break automation but it also now runs contrary to the access instructions on the IBM Cloud console. 

Can we have this put back in?

**Comment by srl295** [comment]
There is a `--yaml` command but it doesn't work.

**Comment by steveclay** [comment]
In the most recent versions of the `ks` plug-in, this is working. You can `ibmcloud ks cluster config <your cluster> --output yaml`
