### ISSUE TITLE
Breaking change 1.?.0 - resource service-key-create drops Administrator role

### ISSUE THREAD

**Issue by shemau** [IBM-Cloud/ibm-cloud-cli-release#114]
Breaking change 1.1.0 - ibmcloud resource service-key-create drops Administrator role

    ibmcloud resource service-key-create "my-sysdig-key-Administrator" Administrator --instance-name "my-sysdig"
    Creating service key of service instance my-cf-sysdig under account my-account as  me@working-at-home.com...
    FAILED
    Role Administrator was not found. Valid roles are Manager, Writer, Reader.

The command works with `Bluemix_CLI/bin/ibmcloud version 0.22.1+66bb68d-2020-02-18T08:26:00+00:00`
It fails with `ibmcloud version 1.1.0+cc908fe-2020-04-29T04:06:12+00:00` as above when logged in with the same account.

**Comment by archerzz** [comment]
@shemau That's correct. We've migrated to new version of API. `ROLE` is optional starting version `1.1.0`. See `Updated Commands` in https://github.com/IBM-Cloud/ibm-cloud-cli-release/releases/tag/v1.1.0

`Administrator` role is actually not meaningful for services which are not IAM-enabled.
