### ISSUE TITLE
'ks' is not a registered command

### ISSUE THREAD

**Issue by fatia64** [IBM-Cloud/ibm-cloud-cli-release#116]
I get an error when I use the command: ibmcloud ks cluster-config mycluster. The error is 'ks' is a not registered command. 

![image](https://user-images.githubusercontent.com/65359366/81963235-bd6c8080-960c-11ea-9d5b-ed6ad20b8aa9.png)

**Comment by archerzz** [comment]
@fatia64 You need to install the `kubernetes-service` plugin. Run `ibmcloud plugin install kubernetes-service`
