### ISSUE TITLE
'tg locations --output json' prints unexpected 'OK' at the begining 

### ISSUE THREAD

**Issue by j4zzcat** [IBM-Cloud/ibm-cloud-cli-release#118]
$ ibmcloud --version
ibmcloud version 1.1.0+cc908fe-2020-04-29T04:06:12+00:00
$ ibmcloud login -r us-south
...
$ ibmcloud tg locations --output json
OK                                                                                                                              
[
    {
        "name": "us-south",
        "type": "region"
    },
    {
        "name": "us-east",
        "type": "region"
    },
    {
        "name": "au-syd",
        "type": "region"
    },
    {
        "name": "eu-de",
        "type": "region"
    }
]

**Comment by kennburger** [comment]
Fixed in tg-cli plugin version 0.2.0

ibmcloud tg locations --output json
[
    {
        "billing_location": "us",
        "name": "us-south",
        "type": "region"
    },
...
]
