### ISSUE TITLE
No consistent way to get json output

### ISSUE THREAD

**Issue by j4zzcat** [IBM-Cloud/ibm-cloud-cli-release#119]
Hello,

JSON output is a common property to nearly all cli commands. 
However, there's no consistent way of getting the json output - some commands accepts '--json', others '--output json'.

Please provide a consistent way to get json output from all cli commands.

**Comment by steveclay** [comment]
Sorry for the confusion. The standard is `--output json`. The plug-in teams are moving to this standard, but not all are there just yet.
