### ISSUE TITLE
Unable to create org space with bx command

### ISSUE THREAD

**Issue by raghvendra1218** [IBM-Cloud/ibm-cloud-cli-release#12]
Hi team,

 I have tried with almost all possible names (sober and weird names), but unable to create org space. seems like there is some issue with my account, don't know. 
![screen shot 2017-11-06 at 3 40 43 pm](https://user-images.githubusercontent.com/32425619/32469752-004c76d2-c309-11e7-9e3c-0747045a11c1.png)
I am also attaching the log file which contains the set of commands which i had use in terminal
[logs.docx](https://github.com/IBM-Bluemix/bluemix-cli-release/files/1448209/logs.docx)

**Comment by archerzz** [comment]
@raghvendra1218 the response indicates that the name `unique1` was taken by others, please try another name.

**Comment by raghvendra1218** [comment]
No I haven't created any orgs before, but my peers with different orgs name are able to create the org as well as space. I am getting this problem, also i am able to use the org which was created for us-south account, as soon as i login with different region , I am able to successfully login , but unable to create any org and neither i see any orgs listed using the command "i am orgs". In us-south account i am unable to create the kubernettes cluster,s o i need to find out why unlike other's, my account is prohibiting me to create org in different region.
Your help will be much appreciated. Thank you!

**Comment by boyang9527** [comment]
pls let me know your account type

**Comment by raghvendra1218** [comment]
I am an Student at SJSU, we have free trail period for 6 months. I am
really sorry i am not sure which account type i have to mention here. can
you provide me with the options, that would be very helpful.

Thank you

**Comment by ogunsegun** [comment]
Please am a student from Nigeria I sign up for free on ibmcloud for training on you nation Africa courses. Please am having problem on no org and space sir my email is soguntunnbi@gmail.com. please I need your help, am unable to push my app
