### ISSUE TITLE
Nothing proceeds further after running & installing IBM_Cloud_CLI_1.1.0_amd64.exe

### ISSUE THREAD

**Issue by ybadri** [IBM-Cloud/ibm-cloud-cli-release#123]
I do not know what to do after windows installation .. there is no interface shown in the directory

**Comment by steveclay** [comment]
@ybadri are you still having this problem? The installer will instruct you on the 1st install on Windows to reboot your system. This will put the CLI in your system path and you will be able to run `ibmcloud` from a command prompt.
