### ISSUE TITLE
Could not find compatible binary to install for plug-in cloud-functions/wsk/functions/fn.

### ISSUE THREAD

**Issue by Edwin-Luijten** [IBM-Cloud/ibm-cloud-cli-release#127]
I'm trying to install the cloud-functions plugin but it's failing.

**OS:** ubuntu:18.04
**Installation steps:**  
```
curl -fsSL https://clis.cloud.ibm.com/install/linux | sh  
ibmcloud plugin install cloud-functions
```  

**Result:** Could not find compatible binary to install for plug-in cloud-functions/wsk/functions/fn.

**Comment by saulotdr** [comment]
I have the same issue here.

![image](https://user-images.githubusercontent.com/45673271/86849875-b8fd9a80-c086-11ea-9027-b1a809e4aaa5.png)

**Comment by Edwin-Luijten** [comment]
It seems to work now.

**Comment by saulotdr** [comment]
It's working here too

**Comment by Edwin-Luijten** [comment]
Cool, closing it because it seems it was a fluke.
