### ISSUE TITLE
Could not find compatible binary to install for plug-in container-service/kubernetes-service.

### ISSUE THREAD

**Issue by carpemonf** [IBM-Cloud/ibm-cloud-cli-release#128]
I got this error when trying to install `ibmcloud plugin install container-service` (ppc64le and RHEL 7.3).

`ibmcloud login` or installation of `container-registry` plugin worked.

Thanks.

**Comment by archerzz** [comment]
@carpemonf I've forwarded to `container-service` team. Thanks.

**Comment by steveclay** [comment]
@carpemonf is your problem now resolved?

**Comment by carpemonf** [comment]
Yes, I got the binaries for ppc64le that solved the issue.

Thank you.
