### ISSUE TITLE
Are there plans to have a release against ARM platform?

### ISSUE THREAD

**Issue by amprasanna** [IBM-Cloud/ibm-cloud-cli-release#13]
Hello Team,

I don't get to see a build specific to ARM platform / architecture. Hence, I presume it's safe to assume that there isn't one at this point of time.
Should this be the case, can you please let us know, if there are plans scheduled for a release against ARM platform in the near future? Or, is it too early as of now.

**Comment by boyang9527** [comment]
we don't have strong requirements for ARM support right now. We will consider this if there is in the future.
