### ISSUE TITLE
armv6l support

### ISSUE THREAD

**Issue by phssakaigawa** [IBM-Cloud/ibm-cloud-cli-release#131]
I'd like to use on raspberry pi

We team build TJBot HandsOn Environment on Raspberry pi.
I would like to use the ibmcloud command to order the Watson services I need

```
Unsupported Linux architecture: armv6l. Quit installation.
```

best.

Shoichiro Sakaigawa 
IBM Champion
TJBotFAN

**Comment by archerzz** [comment]
Hi @phssakaigawa The support of `armv6` was dropped long time ago in Go: https://github.com/golang/go/issues/17082

So we cannot support `armv6l`, since our CLI is written in Go and our general principle is to support mainstream architecture.
