### ISSUE TITLE
No API endpoint set. Use 'cf login' or 'cf api' to target an endpoint.（cf 6.52.0 only）

### ISSUE THREAD

**Issue by IRN-Kawakaze** [IBM-Cloud/ibm-cloud-cli-release#132]
OS：CentOS 7
ibm-cloud-cli：v1.2.0 linux 64bit binary

This problem only occurs in the “cf 6.52.0+b086fe522.2020-08-26” version of cf.

Ways to reproduce the problem：
`ibmcloud login`
`ibmcloud target -g $RESOURSE_ID`
`ibmcloud target --cf`
`ibmcloud cf install`or`ibmcloud cf install -v 6.52.0`
`ibmcloud cf api`or`ibmcloud cf apps`or`ibmcloud cf restart $APP_NAME`
##
Invoking 'cf restart ***'...

No API endpoint set. Use 'cf login' or 'cf api' to target an endpoint.
FAILED
##

Even if I try `ibmcloud target --cf`or`ibmcloud cf api https://api.us-south.cf.cloud.ibm.com`, it still can't get API endpoint.

Is it because the new version changed something or did I do something wrong?（These commands work normally in version 6.51.0）

**Comment by mbvreddy** [comment]
I am also seeing the same issue after upgrade. Any update? It is breaking our deployment. Is there any alternative, like installing lower version until this issue is resolved?

**Comment by benjiewheeler** [comment]
I'm also stuck with this issue for hours, the only workaround I got was to just downgrade to v6.51.0.

By running
`ibmcloud cf install -f -v 6.51.0`

**Comment by archerzz** [comment]
@IRN-Kawakaze @mbvreddy @benjiewheeler This is actually a regression in CF CLI `6.52.0`: https://github.com/cloudfoundry/cli/issues/2096
We've made some work-around in release `1.3.0`.
