### ISSUE TITLE
Travis build failing due to idt installer script pointing to https://download.docker.com/linux/rhel/7/x86_64/stable/repodata/repomd.xml throwing 404 Error.

### ISSUE THREAD

**Issue by akash355** [IBM-Cloud/ibm-cloud-cli-release#133]
We are using the idt installer script [https://ibm.biz/idt-installer](url) in our repos but recently we notice the travis builds are throwing error as mentioned below.

**Errors during downloading metadata for repository 'docker-ce-stable':
  Status code: 404 for https://download.docker.com/linux/rhel/7/x86_64/stable/repodata/repomd.xml (IP: 13.225.222.25)
Error: Failed to download metadata for repo 'docker-ce-stable': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried**

We seeing the above error occurring due to the code in the idt installer script where the docker installation is happening.

The issue has occured due to the change in repo structure on the docker website [https://download.docker.com/linux/rhel/7/](url) x86_64 is folder is no more there. Attached screenshot of the webpage for reference.
![44F3D695-6A8E-417E-A798-CDFBCBC63E8A](https://user-images.githubusercontent.com/30654604/91550614-6cc42d80-e946-11ea-9a54-49a5daf855ee.jpeg)

Kindly update the idt installer script to point to correct folder so that docker-ce.repo hits to correct baseurl and this error does not repeat.

**Comment by steveclay** [comment]
Thank you for your analysis.

As I looked closer in the script, in the docker install section of the IDT installer script https://github.com/IBM-Cloud/ibm-cloud-developer-tools/blob/95c85db7c2ccf539529e4754f258149fa2642656/linux-installer/idt-installer#L278 the code is just invoking `curl -fsSL get.docker.com` which accesses a script from docker.com that does the appropriate install. It appears that this script from docker.com is not handling the new directory structure, properly.

In the meantime, to install Docker manually you can follow these instructions if it is needed in your Travis build: https://docs.docker.com/engine/install/ . I do not expect the overall IDT install to fail for this failing prereq.

Sorry for the inconvenience.

**Comment by akash355** [comment]
Thank you for your reply @steveclay for now will follow the manual installation steps. But What would be the permanent fix here to wait for the docker team to update the script at their end. Can this issue be reported to them , to make them aware or is it an already known issue?

**Comment by akash355** [comment]
I have raised an issue with docker forum as well to look into this https://forums.docker.com/t/docker-installation-failing-due-to-change-in-repo-structure/98202?u=akash355
