### ISSUE TITLE
Verify macOS Binaries with spctl

### ISSUE THREAD

**Issue by salmoidforwork** [IBM-Cloud/ibm-cloud-cli-release#134]
I followed instructions on [Verify Binaries page](https://github.com/IBM-Cloud/ibm-cloud-cli-release/wiki/Verify-Binaries) and it does not work for the latest release I downloaded.  I am running macOS Mojave version 10.14.6.

I entered command like this 
`spctl -a -t open --context context:primary-signature -v ~/myapps/IBM_Cloud_CLI_1.2.0_macos.tgz` 

And it comes back with 
```
/Users/ricks/myapps/IBM_Cloud_CLI_1.2.0_macos.tgz: rejected
source=no usable signature
```
The tgz seems fine. I was able to expand it and use it.

**Comment by archerzz** [comment]
@salmoidforwork `.tgz` is not a binary file. You need to de-compress this file, and run `spctl` against the `ibmcloud` binary.
