### ISSUE TITLE
Release new version of ibmcli

### ISSUE THREAD

**Issue by ko101** [IBM-Cloud/ibm-cloud-cli-release#135]
Some changes was done in slcli and its now merge ,so kindly pull the updates from slcli 

https://github.com/softlayer/softlayer-python/commit/8a19129aea820c7932bb6b4a83aa688813a18295

**Comment by allmightyspiff** [comment]
Code for this is in https://github.ibm.com/Bluemix/bluemix-cli/pull/3283

**Comment by archerzz** [comment]
@ko101 We've published version `1.3.0` which includes the changes. Thanks.
