### ISSUE TITLE
No target Org or Space found

### ISSUE THREAD

**Issue by giucesar** [IBM-Cloud/ibm-cloud-cli-release#136]
Hi.
I'm trying to use the cloud-functions plugin and it is failing to detect that the target is set.

To reproduce:

```
ibmcloud login --sso
ibmcloud plugin install cloud-functions -v TRIEDEVERYVERSIONAVAILABLE
ibmcloud target --cf
ibmcloud fn list
```

After the third command, the terminal confirms that I'm connected to the desired space and org.

```
API endpoint:      https://cloud.ibm.com
Region:            us-east
User:              MY E-MAIL
Account:           MY ACCOUNT
Resource group:    No resource group targeted, use 'ibmcloud target -g RESOURCE_GROUP'
CF API endpoint:   https://api.us-east.cf.cloud.ibm.com (API version: 2.152.0)
Org:               MY ORG
Space:             MY SPACE
```

The issue is when I try to do anything with `ibmcloud fn`, it returns:

`A target Org and Space must be specified. Use 'ibmcloud target --cf' or 'ibmcloud target -o ORG -s SPACE' to set these values.`

**Comment by giucesar** [comment]
To add.

ibmcloud cf commands work without any issue. I can push and manager my apps with it.

**Comment by archerzz** [comment]
Hi @giucesar Would you mind if you could let me know the version of CLI and `functions` plugin? Thanks.

**Comment by giucesar** [comment]
Hi. Sorry for not updating the issue. I contacted IBM support and they updated the tool. It is working now.

**Comment by steven0711dong** [comment]
@giucesar So after you updated the tool, are you still seeing the message after the 3rd command?

**Comment by giucesar** [comment]
After the update, it is working as intended. 
On the third command, it shows the information about my environment. On the fourth, it properly identifies the connected FN and lists all functions (among all other ibmcloud fn commands).
