### ISSUE TITLE
Different Results from ks cluster ls when --output Specified

### ISSUE THREAD

**Issue by bparrill** [IBM-Cloud/ibm-cloud-cli-release#138]
We have a number of clusters and all but one are Classic.  The one exception is vpc-gen2.

Using `ibmcloud ks cluster ls` to list them shows all clusters.

However, `ibmcloud ks cluster ls --output json` is one short and doesn't list the one cluster that's vpc-gen2.

Is it possible to get all clusters in json format with a single call?  I tried using multiple `--provider` arguments but it only accepts the last one.

**Comment by bparrill** [comment]
Is this not the right place to ask these questions?

**Comment by steveclay** [comment]
@JohnStarich could you address this question?
