### ISSUE TITLE
Config to remove "Invoking command'..."

### ISSUE THREAD

**Issue by hphde** [IBM-Cloud/ibm-cloud-cli-release#141]
At least the cf plugin has the feature to curl and return JSON but because the ibmcloud command prints out
```
Invoking 'cf curl '...

```
first further processing of the JSON output breaks without further tweaks.

I think it would be neat to suppress that output to have a consistent look & feel for "ibmcloud cf curl ..." and "cf curl ..."

My current workaround is to define a function (bash or zsh) before invoking cf commands:
```
cf() { ibmcloud cf "$@"|tail -n+3; }
```

**Comment by archerzz** [comment]
@hphde Try `-q` flag. It works for me as follows:

```
ibmcloud cf curl /v2/apps -q | jq
```
