### ISSUE TITLE
Changelog too short - Please document all your changes

### ISSUE THREAD

**Issue by jmgalvez** [IBM-Cloud/ibm-cloud-cli-release#145]
Hello there,

We heavily use your ibmcloud cli and we have some automation using it. It is a pity that you do not share your source code...anyway..

From 1.2.3 to 1.3.0 the command **ibmcloud iam access-group-service-ids xxx --output json** has changed the output. The json is totally different. 

Not sure if you have modified more commands...

It would be **very nice** if you document **ALL your changes** affecting every single command. I think your current CHANGELOG might be improved, at least for mayor and minor versions.

**Comment by archerzz** [comment]
@jmgalvez Sorry for the breaking changes. We've migrated to new version of APIs, which previously we did not mention in change log.

I've updated the change log to reflect the API migration: https://github.com/IBM-Cloud/ibm-cloud-cli-release/releases/tag/v1.3.0

From now on, we'll include those types of changes in our change log.
