### ISSUE TITLE
ibmcloud kubernetes-service plugin ignoring --check-version false

### ISSUE THREAD

**Issue by lauksas** [IBM-Cloud/ibm-cloud-cli-release#149]
Hello,
it seems that the kubernetes-service plugin is ignoring the `--check-version false` flag and the environment variable `IBMCLOUD_VERSION_CHECK="false"`. At least in the public docker image ibmcom/ibm-cloud-developer-tools-amd64:latest
This is bad for pipeline scripts which relies in the flag to not expect for user input.

Workaround:
I tried to issue the command `ibmcloud plugin update kubernetes-service` in my Dockerfile which inherits from the oficial image, it was still trying to update, even if in the latest version it was complaining.

I thought, some state is not being saved after upgrade, so I tried issuing the update command twice, and it worked. Dockerfile below is what I used:

```
FROM ibmcom/ibm-cloud-developer-tools-amd64:latest
RUN ibmcloud config --check-version=false && \
    ibmcloud config --usage-stats-collect false && \
    ibmcloud config --color false
RUN apk add --update --no-cache curl tar bash openssl \
    && curl -sL https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
ENV ENV="dev" \
    IBMCLOUD_API_KEY="" \
    PROGRAMATIC_MODE="true" \
    DESIRED_VERSION="v2.16.12" \
    HELM_HOME="~/.helm"
```

**Comment by steveclay** [comment]
That image is an as-is image, unfortunately. It appears to be out-of-date. Apologies for the inconvenience.

**Comment by lauksas** [comment]
> That image is an as-is image, unfortunately. It appears to be out-of-date. Apologies for the inconvenience.

Not a problem, thought on reporting because it has a workaround someone else can use. Haven't tested with newer versions to check if the bug still valid.
