### ISSUE TITLE
IBM Cloud CLI Cloud Object Storage (COS) plugin is not installing on windows 64 bit machine

### ISSUE THREAD

**Issue by Gaurav-Ramakrishna** [IBM-Cloud/ibm-cloud-cli-release#150]
IBM Cloud CLI Cloud Object Storage (COS) plugin is not installing on windows 64 bit machine. Its throwing the following error,
`Looking up 'cloud-object-storage' from repository 'IBM Cloud'...
FAILED 
Could not find compatible binary to install for plug-in cloud-object-storage.`
![installIssueWindows](https://user-images.githubusercontent.com/60436767/109179558-0767c280-7758-11eb-9d9e-a62809ce1473.PNG)

**Comment by steveclay** [comment]
I am unable to recreate this problem. Can you successfully ping plugins.cloud.ibm.com ?

![image](https://user-images.githubusercontent.com/10873292/109201975-12c2ea00-7768-11eb-8c07-16da797049ae.png)

**Comment by Gaurav-Ramakrishna** [comment]
Yes I'm able to successfully ping plugins.cloud.ibm.com
![image](https://user-images.githubusercontent.com/60436767/109204143-0001e280-7773-11eb-8e8a-eba595cfe0a8.png)

**Comment by steveclay** [comment]
Has this problem now been corrected for you? I'm still not seeing this failure.

**Comment by Gaurav-Ramakrishna** [comment]
![installIssueWindows2](https://user-images.githubusercontent.com/60436767/129118097-1412ab14-0f35-4801-86f7-619394334af1.PNG)

Nope, I still have the issue.
When I list the plugins I can see the `cloud-object-storage` plugin. But when I try to install it fails.
Also, the IBM Cloud CLI version is 2.0.2

**Comment by steveclay** [comment]
OK. Is `cloud-object-storage` the only plug-in you cannot install. If you try to update or install others, what results do you see?

**Comment by Gaurav-Ramakrishna** [comment]
![installIssueWindows3](https://user-images.githubusercontent.com/60436767/129219182-daec642d-6fc6-411f-aa10-af1113a58aae.PNG)

You can notice in the above image, 

- I have some plugins already installed.
- I could successfully install `cloudant` plugin.
- But when I try to install `cloud-object-storage` it fails.

**Comment by steveclay** [comment]
I am reaching out to the team that develops this plug-in for assistance as I have been unable to recreate this problem. I am suspecting that your system may not be recognized as a Win64 system. That is my best guess at this point because this plug-in does not support 32 bit Windows. If you have Golang installed, you can run `go env` to see if Golang recognizes your system as being 64 bit (the `GOARCH` field).

**Comment by steveclay** [comment]
I believe this is now resolved. Please reopen if you continue to have trouble.
