### ISSUE TITLE
ml not compatible with WML v4 API

### ISSUE THREAD

**Issue by tatsubori** [IBM-Cloud/ibm-cloud-cli-release#152]
Hi,

Now I cannot use Machine-Learning plugin (ml) CLI for accessing the latest Watson Machine Learning V4 API.  Is this as intended, or am I wrong in usage?

```
% ibmcloud ml list frameworks      
Fetching the list of frameworks ...
FAILED
Unable to get /v3/wml_instances/ed3465d6-8eb8-4e2d-bb8e-454218ef57d5 [400]: {"trace":"b40fa330bf946aa30c955e56837dc519","errors":[{"code":"invalid_request","message":"Instance in v2 plan should use v4 API."}]}

TraceId: 2ba59f177e99b1dd2be169fecfbdd09c
```

Here are version infos.

```
% ibmcloud version
ibmcloud version 1.4.0+4705d79-2021-02-24T21:58:03+00:00

% ibmcloud ml version
Git Commit Hash: b4625b1df6044890c421687676151687597c3264
UTC Build Time : 20190716.084640
Plugin Version : 3.0.2
```

**Comment by steveclay** [comment]
This article states that only v1 is supported by this plug-in:  https://dataplatform.cloud.ibm.com/docs/content/wsj/analyze-data/ml_dlaas_environment.html . Apologies for the confusion, the plug-in is going to be removed as it is no longer usable with the current versions of wml.
