### ISSUE TITLE
Please use semantic versioning

### ISSUE THREAD

**Issue by ert78gb** [IBM-Cloud/ibm-cloud-cli-release#153]
Please change the major version number if you know the release contains BREAKING CHANGES.

[Semantic versioning](https://semver.org/) helps to identify breaking changes without read the release notes. 

thx

**Comment by boyang9527** [comment]
thanks for pointing out.   v1.3.0 does have breaking changes and we should change the major version number.  We definitely will follow the semantic versioning in the future releases. Again thanks!

**Comment by ert78gb** [comment]
You are welcome. I close this issue I think you will remember for it. If you need you can reopen it.
