### ISSUE TITLE
ibmcloud plugin update

### ISSUE THREAD

**Issue by sreeteja7** [IBM-Cloud/ibm-cloud-cli-release#154]
So update -r flag is not case sensitive BUT it is trying to fetch information from the actual repo here in our case 'test' BUT displaying in the console message as the parameter that is passed 'TEst'

Same dont apply for the plugin that is upgraded

<img width="1071" alt="Screenshot 2021-03-16 at 10 31 06 PM" src="https://user-images.githubusercontent.com/26268079/111417200-5bd4e100-870b-11eb-9e45-41968e86e4ed.png">

It will be nice to have the case insensitive repo parameter also printed likewise
vresion: ibmcloud version 1.4.0+4705d79-2021-02-24T21:18:06+00:00

**Comment by steveclay** [comment]
@sreeteja7 I'm not sure I understand what you are reporting. The CLI outputted the same casing of the value that was input. This is generally expected behavior from what I see. In this case the input did not match the real repo definition, but this cannot be corrected by the CLI and still honor the use of mixed casing for repo names.

**Comment by sreeteja7** [comment]
@steveclay there is a difference here in Repo name and Plugin name 

```TEst``` is passed it takes as ```test``` BUT it is printing repo name again as ```TEst``` instead of ```test```(actual value)

This is not the case with plugin name ```hpvS``` is passed it takes as ```hpvs``` and print ```hpvs``` only

**Comment by steveclay** [comment]
@sreeteja7 I see the problem now. We have created an internal issue for tracking this. It appears that you are an IBMer based upon your plugin repo use. You can follow the solution in our internal Github and I will close this ticket.

**Comment by sreeteja7** [comment]
Thanks @steveclay
