### ISSUE TITLE
how to access cloud shell using cli

### ISSUE THREAD

**Issue by trgcyln** [IBM-Cloud/ibm-cloud-cli-release#155]
I was wondering if I can access to cloud.ibm.com/shell using ibm cloud cli

**Comment by steveclay** [comment]
There is not an explicit command for opening the Cloud Shell terminal from the IBM Cloud CLI. Was this what you had in mind or some other use case?

**Comment by trgcyln** [comment]
> There is not an explicit command for opening the Cloud Shell terminal from the IBM Cloud CLI. Was this what you had in mind or some other use case?

so right now ibm cloud shell is only accessible from web browser ? am i right ?  I was expecting to  access it like google such as "gcloud beta cloud-shell"

**Comment by hartyt** [comment]
@trgcyln Cloud Shell does not currently support accessing the remote session remotely via the CLI as you have suggested
