### ISSUE TITLE
login issues using an apikey with a leading "-"

### ISSUE THREAD

**Issue by CGA-WORK** [IBM-Cloud/ibm-cloud-cli-release#158]
we updated our ibmcloud cli recently from 1.4.0 to 1.5.1 since than we are facing the issue that logging in to ibmcloud via cli is not working anymore if you use a apikey which has a leading "-".

For example if I try to login via 
          ibmcloud login -a ${IBMCLOUD_URL} --apikey "-MY_API_KEY" -r eu-de

 this will not work.

 If I try to login via apikey and use the file operator like
         ibmcloud login -a ${IBMCLOUD_URL} --apikey @"${MY_API_KEY}" -r eu-de

this is working. Of course the json file contains the same apikey with the leading "-" as in the String above.

So as summary: logging in via ibmcloud cli is not possible if you use an apikey with a leading "-" and you use the apikey as String parameter.

Before updating to ibmcloud cli 1.5.1 everything was working as expected.

**Comment by steveclay** [comment]
@CGA-WORK are you saying that prior to **1.5.1** with the same API key with the leading "-" you were able to login? From our investigation into this, the order seems to be a key factor in how the underlying Golang interprets the command line. If you juxtapose `--api-key "-thekey"` and `-r eu-de` this should not fail. I.e. `ibmcloud login -r eu-de --apikey "-thekey"`

**Comment by steveclay** [comment]
Closing with the alternative that was provided. Further research has shown this is a general parsing problem of command line flags in Golang for which there is not a fix at this time.
