### ISSUE TITLE
How to download a application instance runing at bluemix

### ISSUE THREAD

**Issue by cjjchu** [IBM-Cloud/ibm-cloud-cli-release#16]

**Comment by archerzz** [comment]
@cjjchu would you please provide more background information? Do you want to get the application source code?

**Comment by cjjchu** [comment]
Yes,there is a nodejs application in bluemix，we want to get the sorce code.

**Comment by boyang9527** [comment]
if it is a CF application,  use 'bx cf ssh' to ssh into the container and get the source code.
