### ISSUE TITLE
Problems with upgrading client from 1.4 to newer versions

### ISSUE THREAD

**Issue by mbirch-ca** [IBM-Cloud/ibm-cloud-cli-release#160]
Currently I am running version 1.4.0+4705d79-2021-02-24T21:18:06+00:00 of the IBM Cloud CLI on Windows 10.

Since the release of version 1.5, I have found that the update mechanism attempts to download the latest version but the installer fails.  With the recent release of version 1.6, I see the same behaviour including when downloading the installer and running it locally.  The prompt states
> A later version of 'IBM Cloud Command Line Interface' is already installed on this machine.  The setup cannot continue
Enabling [debug logging for the installer](https://docs.microsoft.com/en-US/troubleshoot/windows-client/application-management/enable-windows-installer-logging) does not provide much details other than one line where it states "Determined that existing product (either this product or the product being upgraded with a patch) is installed per-machine"

Seems to be an issue with the installer of the CLI

**Comment by steveclay** [comment]
Thank you for reporting this. We have seen this intermittently for Windows users. Have you tried uninstalling the current CLI and then installing the new version?

**Comment by mbirch-ca** [comment]
I can confirm that uninstalling the client and downloading/installing 1.6 does work but waiting to see for the next update.

As mentioned, I did not get much useful information from the install log but can try and reproduce if that helps

**Comment by steveclay** [comment]
Thank you. 

In some tests that I did, after uninstalling and then installing, I was no longer able to reproduce the problem on subsequent updates (for example to 1.6). But this seems to be very intermittent as not all Windows systems ever showed the problem.

**Comment by SathishN** [comment]
+1, I have 1.4, not able to update to any new version. 
When I install 1.2, it says 'Later version of Command Line Interface already installed'!

**Comment by steveclay** [comment]
@SathishN is there a reason you need version *1.2.0* ? To move backward, you may need to uninstall the current version before installing the older version. To move forward, you can just use `ibmcloud update`.
