### ISSUE TITLE
Error configuring new Kubernetes cluster with CLI

### ISSUE THREAD

**Issue by bansmani** [IBM-Cloud/ibm-cloud-cli-release#165]
Trying to run below command, but giving me below error, I am using latest CLI version, as mentioned below. 
Can someone please help on this quickly, since 30 days of free trial started today. :)  

```
C:\Users\manish>ibmcloud ks cluster config --cluster my-cluster-id 
FAILED
'ks' is not a registered command. See 'ibmcloud help'.

```
My Version 
```
C:\Users\manish>ibmcloud version
ibmcloud version 2.0.0+5a84b9b-2021-06-23T17:07:07+00:00
```

**Comment by bansmani** [comment]
Ok found a solution, needed to install plugin. 

`ibmcloud plugin install container-service`

Suggestion: IBM cloud dashboard should be more expressive and it would be save users time.

**Comment by steveclay** [comment]
Thank you for these comments. We are always looking to improve the user experience.
