### ISSUE TITLE
pls make v2.0.2 become latest release

### ISSUE THREAD

**Issue by maodou38** [IBM-Cloud/ibm-cloud-cli-release#167]

**Comment by steveclay** [comment]
The marking of *latest* is automatically done by Github. There is not a straightforward way to change this from what I have found. Is this impacting your use of the CLI?

**Comment by maodou38** [comment]
yes,i always get the latest version CLI by using github api.so the version mistake makes me appoint v2.0.2 temporarily. v2.0.1 has mistake and can not installed.
So, maybe you can remove the v2.0.2 and republish again? let github knows the latest version is 2.0.2
