### ISSUE TITLE
ibmcloud pi import-images from COS no longer working

### ISSUE THREAD

**Issue by cunlifs** [IBM-Cloud/ibm-cloud-cli-release#169]
Hi, my Ansible playbook command to import an image into my PowerVS catalogue is no longer working.  I've used the exact same parameters in the GUI and it works fine. I've also checked my logs from a few weeks ago and the syntax is exactly the same.

Login is OK:
**$ ibmcloud login --apikey _xxxx_ -r eu-gb
API endpoint: https://cloud.ibm.com
Authenticating...
OK

Targeted account _xxxx_'s Account (_xxxx_) <-> _xxxx_

Targeted region eu-gb

                      
API endpoint:      https://cloud.ibm.com   
Region:            eu-gb   
User:              _xxxx_@uk.ibm.com   
Account:           _xxxx_'s Account (_xxxx_) <-> _xxxx_  
Resource group:    No resource group targeted, use 'ibmcloud target -g RESOURCE_GROUP'   
CF API endpoint:      
Org:                  
Space:**                

And I set the correct PowerVS service:
**$ ibmcloud pi service-target crn:v1:bluemix:public:power-iaas:lon04:a/_xxxx_::
Targeting service crn:v1:bluemix:public:power-iaas:lon04:a/_xxxx_::...**

But when I try and import the image from COS it fails:
**$ ibmcloud pi image-import app-2-image-awx --image-path s3.eu-gb.cloud-object-storage.appdomain.cloud/eu-gb-bucket1/app-1-image-awx.ova.gz --disk-type tier3 --access-key _xxx_ --secret-key _xxx_  
Importing image from s3.eu-gb.cloud-object-storage.appdomain.cloud/eu-gb-bucket1/app-1-image-awx.ova.gz into account _xxx_'s Account as user _xxx_@uk.ibm.com...
FAILED
Failed to import image.

FAILED
[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/images][400] pcloudCloudinstancesImagesPostBadRequest  &{Code:0 Description:bad request: import image from cloud storage failed: cloud storage access failed, image import requires the cloud storage image filename to be specified Error:bad request Message:}**

---------
This is the correct bucket, path location for file name etc.

**Comment by cunlifs** [comment]
Can anyone comment on this please?

**Comment by steveclay** [comment]
@cunlifs this command is from the `pi` plug-in and not the actual CLI. I am reaching out to this team to assist you.

**Comment by rmoralesjr** [comment]
FYI, we will get back to you soon.

**Comment by rmoralesjr** [comment]
The backend development team said to change s3.eu-gb.cloud-object-storage.appdomain.cloud to s3.private.eu-gb.cloud-object-storage.appdomain.cloud 
I don't have an explanation from them yet on what changed but at least hopefully this will get you working.

**Comment by steveclay** [comment]
@cunlifs did this resolve the issue for you?
