### ISSUE TITLE
Unable to install latest version of CLI

### ISSUE THREAD

**Issue by kalantar** [IBM-Cloud/ibm-cloud-cli-release#177]
The [documented approach](https://cloud.ibm.com/docs/cli/index.html) to install the CLI on Linux:

    curl -fsSL https://clis.cloud.ibm.com/install/linux | sh

Stopped working with the release of version 2.4.0.  Get the following error: 

    Unable to parse installer url and checksum url. Quit installation.

The problem seems to with these lines:

    platform_binaries=$(echo "$metadata_section" | sed -ne '/'"$platform"'/,/'"checksum"'/p')
    ...
    sh1sum=...

`platform_binaries` does not include `"checksum"`

**Comment by steveclay** [comment]
Thank you for reporting. This has now been addressed.
