### ISSUE TITLE
container-service and cloud-functions not available for ppc64le

### ISSUE THREAD

**Issue by rdasgupt** [IBM-Cloud/ibm-cloud-cli-release#179]
On ppc64le OS, getting error while installing cloud-functions and container-service plugins.

$ ibmcloud plugin install cloud-functions
Looking up 'cloud-functions' from repository 'IBM Cloud'...
FAILED
Could not find compatible binary to install for plug-in cloud-functions[wsk/functions/fn].

$ ibmcloud plugin install container-service
Looking up 'container-service' from repository 'IBM Cloud'...
FAILED
Could not find compatible binary to install for plug-in container-service[kubernetes-service].

$ ibmcloud version
ibmcloud version 2.5.0+3bf759b-2022-02-24T21:16:12+00:00

---------
Available plugins in repo:

$ ibmcloud plugin repo-plugins -r 'IBM Cloud'
Getting plug-ins from repository 'IBM Cloud'...

Repository: IBM Cloud
Status          Name                                                        Versions                       Description
Not Installed   dvaas[watson-query]                                1.0.2                          Manage data virtualization as a service
Not Installed   container-service[kubernetes-service]    1.0.374, 1.0.372, 1.0.353...   Manage IBM Cloud Kubernetes Service clusters
Not Installed   analytics-engine                                         1.0.181, 1.0.177, 1.0.174...   Manage Analytics Engine service
Not Installed   cloud-functions[wsk/functions/fn]            1.0.58, 1.0.56, 1.0.54...      Manage Cloud Functions
Not Installed   machine-learning                                       3.0.2, 3.0.1, 2.1.8...         Manage Machine Learning service

**Comment by steveclay** [comment]
Sorry for the confusion here. I will take this as a defect for the `repo-plugins` that it is showing plug-ins that are not actually available on your OS. Neither of the plug-ins you tried to install have a version for ppc64le. Other plug-ins do however, for example `container-registry` should install for you. I will also notify these plug-in teams of your interest on this platform.

**Comment by rdasgupt** [comment]
Any update on this. I have not heard anything from plug-in team. We are currently blocked and can't port our project on ppc64le.

**Comment by rdasgupt** [comment]
@steveclay Could you please give me to a contact in cloud-functions plug-in team?

**Comment by steveclay** [comment]
This is being handled via slack now. Closing.
