### ISSUE TITLE
IBMCloud target resource not working properly

### ISSUE THREAD

**Issue by ahthakur** [IBM-Cloud/ibm-cloud-cli-release#185]
Hi, 

We recently ran into the issue where targetting all the orgs under my cf , I cannot login to it - 

bash-3.2$ ibmcloud target -cf
IBM Cloud Foundry Public is deprecated. For more information, see http://ibm.biz/ibmcf-announce
Targeted Cloud Foundry (https://api.us-south.cf.cloud.ibm.com)

Targeted org Abhijit.Thakur

Targeted space test

                      
API endpoint:      https://cloud.ibm.com   
Region:            us-south   
User:              Abhijit.Thakur@ibm.com   
Account:           Abhijit Thakur's Account (6b9e1afb31ebb7b48f9edd1c8fb64a5a)   
Resource group:    No resource group targeted, use 'ibmcloud target -g RESOURCE_GROUP'   
CF API endpoint:   https://api.us-south.cf.cloud.ibm.com (API version: 2.182.0)   
Org:               Abhijit.Thakur   
Space:             test   
bash-3.2$ Ibmcloud cf orgs
Invoking 'cf orgs'...

Getting orgs as Abhijit.Thakur@ibm.com...

name
Abhijit.Thakur
TJBot Blue Hack Austin
bash-3.2$ ibmcloud 
bash-3.2$ cf target -o 'FabLab-MainOrg
bash-3.2$ ibmcloud target -o 'Abhijit.Thakur'
Targeted org Abhijit.Thakur

                      
API endpoint:      https://cloud.ibm.com   
Region:            us-south   
User:              Abhijit.Thakur@ibm.com   
Account:           Abhijit Thakur's Account (6b9e1afb31ebb7b48f9edd1c8fb64a5a)   
Resource group:    No resource group targeted, use 'ibmcloud target -g RESOURCE_GROUP'   
CF API endpoint:   https://api.us-south.cf.cloud.ibm.com (API version: 2.182.0)   
Org:               Abhijit.Thakur   
Space:                
bash-3.2$ ibmcloud target -o 'TJBot Blue Hack Austin'
FAILED
Could not get org:
Org 'TJBot Blue Hack Austin' was not found under account 'Abhijit Thakur's Account'.

bash-3.2$

If we try it using just cloud doundry cli , we don't runinto this issue. 

Can you please let us know if this is by design and if so what is the explaination for it.

**Comment by TheSgrash** [comment]
Please notice that the `ibmcloud target` commands that are failing are the ones aiming to target to a CF Org of the **same** region but owned by a **different** IBM Cloud Account. 
We looked for such limitation into the docs but there is nothing explaining this behaviour

**Comment by steveclay** [comment]
As we discussed in another thread, the targeting is purposely within the account, not across accounts. This is a convention that the CLI  enforces and is common in IBM Cloud.
