### ISSUE TITLE
Download link for v2.11.1 Mac M1/ARM CLI is broken

### ISSUE THREAD

**Issue by biosopher** [IBM-Cloud/ibm-cloud-cli-release#188]
The download link for the v2.11.1 Mac M1/ARM IBM Cloud CLI is broken here:
https://github.com/IBM-Cloud/ibm-cloud-cli-release/releases/

That page links to this URL which doesn't exist:
[Mac OS X M1/ARM](https://download.clis.cloud.ibm.com/ibm-cloud-cli/2.11.1/IBM_Cloud_CLI_2.11.0_arm64.pkg)  (as-is)

<img width="837" alt="image" src="https://user-images.githubusercontent.com/814855/194582609-d1f8a6c5-48e1-4cc0-b0d1-7e8f5c12c337.png">

**Comment by steveclay** [comment]
The link is corrected on the releases page. Apologies for the inconvenience.
