### ISSUE TITLE
Failed to publish functions from github action

### ISSUE THREAD

**Issue by iksinski** [IBM-Cloud/ibm-cloud-cli-release#192]
Hey,

I'm having problems with publishing ibm cloud function from github action my steps are:

```
      # Download and Install IBM Cloud CLI
      - name: Install IBM Cloud CLI
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud --version
          ibmcloud config --check-version=false
          ibmcloud plugin install -f cloud-functions

      # Authenticate with IBM Cloud CLI
      - name: Authenticate with IBM Cloud CLI
        run: |
          ibmcloud login --apikey "${IBM_CLOUD_API_KEY}" -a https://cloud.ibm.com -r "${IBM_CLOUD_REGION}" -g "${IBM_RESOURCE}"
          
      # Deploy
      - name: Deploy to functions
        run: |
               ibmcloud fn action list //for testing purposes      
```

result is: 
```
A target Org and Space must be specified. Use 'ibmcloud target --cf' or 'ibmcloud target -o ORG -s SPACE' to set these values.
```

Tried running `ibmcloud target --cf` but it doesn't help.

Result of `ibmcloud target` (without running `target --cf`)

```
API endpoint:      https://cloud.ibm.com/
Region:            ***
User:              my-email
Account:           account-details
Resource group:    resource-group
CF API endpoint:   
Org:               
Space:             
```

Plugin version:
```
Plugin Name                         Version   Status   Private endpoints supported
cloud-functions[wsk/functions/fn]   1.0.62             false
```

Locally it works just fine, in actions running it with `ubuntu-latest`.

**Comment by steveclay** [comment]
@iksinski could you share the exact command and output that leads to the warning about targeting with `--cf`? From the description above, it looks like you see this when you `ibmcloud plugin list` which is hard to reconcile with the functionality of the CLI. Thank you

**Comment by iksinski** [comment]
Ohhh, sorry - my mistake, updated the issue - even `ibmcloud fn action list` fails.

**Comment by steveclay** [comment]
Although this command does not explicitly say this, I notice other commands (for example `namespace list`) indicates commands are executed for Cloud Foundry and IAM. I do not see an option to alter this behavior but I will reach out to the team that maintains this plug-in.

**Comment by iksinski** [comment]
Strange this is that it works absolutely fine locally.

What I want to achieve is publishing from gh action, so using `ibmcloud fn action update ...`

**Comment by azieseme** [comment]
Hi @iksinski 

If I get the script (GH action?) right, it just does `ibmcloud login` with some params (e.g. especially `-g <resource-group`), but it is not doing the essential targeting of any Cloud Functions namespace before running the `ibmcloud fn action list`.


You might want to check the following (e.g. manually):
```
ibmcloud login ...
ibmcloud target -g <resource-group>
ibmcloud fn namespace list
```
At this stage, you likely get a list of (recommended) "IAM-based" Functions namespaces or maybe (old deprecated) "CF-based" namespaces.

To work with objects in an "IAM-based" Functions namespace, the script would need to take the following steps:
```
ibmcloud login ... -g <resource-group>
ibmcloud fn namespace target <some-IAM-based-namespace-name-or-id>
ibmcloud fn action list
```

To work with objects in an "CF-based" Functions namespace, the script would need to take the following steps:
```
ibmcloud login ... -g <resource-group> -o <cf-org> -s <cf-space>
ibmcloud fn action list
```

Documentation about IBM Cloud Functions namespaces can be found at https://cloud.ibm.com/docs/openwhisk?topic=openwhisk-namespaces

I hope this helps.

**Comment by iksinski** [comment]
Worked like a charm, thanks so much @azieseme!

Behavior on my local machine (macos) is different though - I don't need to specify namespace list before I update the function. 

Thanks for your help!

**Comment by azieseme** [comment]
:+1: 

---

Not sure if the info is kept in `$HOME/.wskprops` in your platform / wsk/fn plugin version(?)

**Comment by iksinski** [comment]
Correct, sir - it is stored there! I must have added it and forgot. 

Actually I have been looking for some existing config in `~/.bluemix/config.json` - didn't realise there is anything else.
