### ISSUE TITLE
Broken link on the release page

### ISSUE THREAD

**Issue by lra** [IBM-Cloud/ibm-cloud-cli-release#193]
https://github.com/IBM-Cloud/ibm-cloud-cli-release/releases/tag/v2.13.0 links to https://download.clis.cloud.ibm.com/ibm-cloud-cli/2.13.0/binaries/IBM_Cloud_CLI_2.12.0_macos_arm64.tgz which is a 404.
It should link to https://download.clis.cloud.ibm.com/ibm-cloud-cli/2.13.0/binaries/IBM_Cloud_CLI_2.13.0_macos_arm64.tgz

**Comment by steveclay** [comment]
Thank you for pointing this out. The link is now fixed. 👍
