### ISSUE TITLE
bx plugin install command does not enable auto-completing a file

### ISSUE THREAD

**Issue by kweinmeister** [IBM-Cloud/ibm-cloud-cli-release#2]
I am reinstalling new versions of a plugin constantly, and would prefer to have the install command auto-complete the filename (which happens to be very long).

**Expected behavior:**
To compare to the `cf` command... On macOS, I can run `cf install-plugin ` and it will auto-complete the file afterward based on the files in the current directory structure.

**Actual behavior:**
I hit tab repeatedly after typing `bx plugin install ` and nothing happens

**Comment by boyang9527** [comment]
It is in backlog, planned for Sep.

**Comment by boyang9527** [comment]
this feature has been delayed, will give a date once it is planed
