### ISSUE TITLE
The bluemix command line interface shutsdown automatically

### ISSUE THREAD

**Issue by sl2902** [IBM-Cloud/ibm-cloud-cli-release#20]
I installed the 64 bit Windows Bluemix CLI on a Windows 10 Home laptop; the installation went off successfully, but after launching the command line, the window opens for a fraction of a second before closing. I tried uninstalling and installing the exe file as the administrator, but with no luck. Any idea what could be causing this issue?

**Comment by boyang9527** [comment]
please open a command line window, and type 'bluemix' or 'bx' to run it...
