### ISSUE TITLE
Installing on WSL gives advice on using Docker Desktop

### ISSUE THREAD

**Issue by mbwhite** [IBM-Cloud/ibm-cloud-cli-release#201]
If I install the CLI on the WSL2 

```
 => [ 4/12] RUN curl -sL https://raw.githubusercontent.com/IBM-Cloud/ibm-cloud-developer-tools/master/linux-installer/idt-installer   57.5s
 => => # [install_docker] Installing/updating external dependency: docker
 => => # # Executing docker install script, commit: e5543d473431b782227f8908005543bb4389b8de
 => => # WSL DETECTED: We recommend using Docker Desktop for Windows.
 => => # Please get Docker Desktop from https://www.docker.com/products/docker-desktop/
 => => # You may press Ctrl+C now to abort this script.
 => => # + sleep 20
 ```
 
Given -
a) the position of Docker Desktop as a paid offering for another non=IBM provider I think it isn't really appropriate to suggest this. 
b) there is really no practical or technical requirement for WSL2 users to be using Docker Desktop - the open source docker engine is perfectly usable on WSL2 and indeed gives a better development experience.

**Comment by steveclay** [comment]
@mbwhite apologies for any confusion, but you are using a method of installing the CLI that is no longer supported. For supported installation techniques, please see https://cloud.ibm.com/docs/cli?topic=cli-getting-started
