### ISSUE TITLE
[BUG] Targeting a resource group containing a space causes errors

### ISSUE THREAD

**Issue by awarrier99** [IBM-Cloud/ibm-cloud-cli-release#202]
Hi there, thank you for maintaining this CLI, it has been very useful for our team's automations.

I'm noticing that targeting a resource group with a space in the name (even when properly double-quoted) has now broken in version 2.21.0 of the CLI (`2.21.0+c3b707578-2023-10-24T22:40:54+00:00`). I have confirmed that this command (`ibmcloud target -g "Example Resource Group"`) works with no issue on the previous CLI versions (tested on systems that either hadn't upgraded yet or that we manually installed version 2.20.0 via the previous release binary).

For reference, this is the error encountered:
```
FAILED
Could not get resource group:
The following error(s) occurred:
Failed to get a resource group.

Trace ID: <...>
```

Thanks!

**Comment by steveclay** [comment]
@awarrier99 sorry for the inconvenience. This problem is being worked as the CLI has exposed a problem with the resource API. In the meantime, I suggest downgrading to the previous release https://github.com/IBM-Cloud/ibm-cloud-cli-release/releases/tag/v2.20.0 . Sorry that this might not be as easily resolved in your devops.

**Comment by awarrier99** [comment]
Hi @steveclay thanks for your quick response and for letting me know! No problem, I actually had just updated my original post at pretty much the exact same time haha - we were able to configure our deployment instance to install from the previous release binary

**Comment by steveclay** [comment]
> Hi @steveclay thanks for your quick response and for letting me know! No problem, I actually had just updated my original post at pretty much the exact same time haha - we were able to configure our deployment instance to install from the previous release binary

That is great news. This is actively being worked and so I expect a resolution soon.

**Comment by Eric-Arellano** [comment]
Hey @steveclay, is the fix for this still in progress? Thanks!

**Comment by steveclay** [comment]
@Eric-Arellano this should now be corrected.

**Comment by Eric-Arellano** [comment]
Confirmed this now works in https://github.com/Qiskit/documentation/pull/1103 when installing via `curl -fsSL https://clis.cloud.ibm.com/install/linux | sh`. Thanks!
