### ISSUE TITLE
ibmcloud pi plugin. For power iaas. Image list catalog : missing flag for VTL image

### ISSUE THREAD

**Issue by surajsbharadwaj** [IBM-Cloud/ibm-cloud-cli-release#205]
Hello team,
Feature missing for Power plugin.

`ibmcloud pi `plugin has a **limitation** for listing of catalog images for **vtl images**

It currently supports:
`ibmcloud pi image lc `
and
to list **sap images** flag **s** is passed.
 `ibmcloud pi image lc -s`

However
I am **not able to fetch vtl images** via cli.
It is **possible through terraform whe**re we set flags vtl= true to get vtl images.
Who can make this **enhancement of inserting -v flag ?**

**Comment by steveclay** [comment]
Thank you for bringing this to our attention. We will work with the plug-in team to update its functionality. Since you are also an IBMer, I will close this issue as you have visibility into internal tracking, also.
