### ISSUE TITLE
feature: support multiple profiles in the cli

### ISSUE THREAD

**Issue by yoav-orca** [IBM-Cloud/ibm-cloud-cli-release#207]
Support a flag to switch between profiles and regions. Similar to all other cloud providers CLI-s (aws-cli, azure-cli, gcp-cli, ocli, aliyun-cli) 
Something like:
```
ibmcloud --profile profile1 --region eu-de is volumes list
ibmcloud --profile profile2 --region us-east is volumes list
```

**Comment by steveclay** [comment]
@yoav-orca thank you for this submission.

**Comment by steveclay** [comment]
@yoav-orca please see the new `trusted-profile-assume` and related commands in [release 2.26.0](https://github.com/IBM-Cloud/ibm-cloud-cli-release/releases/tag/v2.26.0). This seems along the lines of what you are looking for.
