### ISSUE TITLE
Bluemix CLI Download Issue

### ISSUE THREAD

**Issue by Renu5** [IBM-Cloud/ibm-cloud-cli-release#21]
Hello,
I am not able to download Bluemix CLI.. I am getting a timeout issue. Can i please know , how i can download this ?

Thanks in advance!
Renu

**Comment by boyang9527** [comment]
are you able to access https://public.dhe.ibm.com/cloud/bluemix/cli/bluemix-cli/0.6.5/ ?

**Comment by hongsenliu** [comment]
https://clis.ng.bluemix.net/download/bluemix-cli/0.6.6/* does not work for any OS systems such as Win 64, osx and linux 64. However, the previous versions of bluemix-cli are good for access. Unfortunately, `bx update` from my current bluemix cli has  the same issue which  is exceeding maximum redirections.

**Comment by boyang9527** [comment]
should be fixed now.
