### ISSUE TITLE
Incorrect error is reported while creating configmap for code engine

### ISSUE THREAD

**Issue by RahulMetangale** [IBM-Cloud/ibm-cloud-cli-release#210]
While creating configmap using IBM cloud cli, if configmap name contains underscore command fails with an error
"_A configmap name must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character_"

Steps to reprodcue the issue
`ibmcloud target -g $CODE_ENGINE_RESOURCE_GROUP_NAME -r $CODE_ENGINE_REGION`
`ibmcloud ce project select -n $CODE_ENGINE_PROJECT_NAME. `
`ibmcloud ce configmap create --name "sample_config_map" --from-literal "target=$instances_details_json"`

Error indicates underscores are supported where as that is not the case. following works when name does not contain underscore
`ibmcloud ce configmap create --name "sampleconfigmap" --from-literal "target=$instances_details_json"`

**Comment by michael-magrian** [comment]
Hi @RahulMetangale,
it may be hard to read since the characters look very similar, but what the error message states is that you can use **dashes**, but not **underscores**.
`-` YES, allowed
`_` NO, not allowed
In your example this means you need to change it to the following:
```
ibmcloud ce configmap create --name "sample-config-map" --from-literal "target=$instances_details_json"
```

Hope that helps 🙂

**Comment by steveclay** [comment]
Please reopen if this does not answer your concern. Thank you
