### ISSUE TITLE
IBM Cloud CLI won't let me type my password or One-time code

### ISSUE THREAD

**Issue by Dhyaan1** [IBM-Cloud/ibm-cloud-cli-release#213]
I have just started to use the IBM cloud CLI by following the ibm-cloud-professional-developer-616 course
So i am using 
# Release version v2.27.0 on Windows
After i installed IBM cloud CLI and installed the container-register plug-in i went to the next step which is to sign in
using the command
``` bash
ibmcloud login
``` 
## Username prompt works fine, but the password prompt won't let me type in a password.
But after i put in my email, the password input was not working as much as i tried to type anything, no matter how much nonsense i mashed into my keyboard nothing was being typed
## Using a one-time passcode to log in with the CLI
Then i tried the the command
``` bash
ibmcloud login --sso
``` 
But here after i had received my One-time password, when i go to type it out or paste it. Nothing works again.

I end up having to CTRL + C my way out.

Unless this is a "Feature" of some sorts i don't know what i am supposed to do.
I even typed out my password and the One-time password just assuming that the CLI had decided not to show it to me but was taking in whatever i was typing; It was not. It gave me an error saying my credentials were wrong(Meaning that nothing that i had typed out was being registered)
![image](https://github.com/user-attachments/assets/b7561129-af58-42fd-b4c3-c1bff0d6d82d)
![image](https://github.com/user-attachments/assets/9c7349d7-5b90-441d-96ef-f102f18069bd)

**Comment by steveclay** [comment]
@Dhyaan1 we are not able to reproduce this failure. What version of Windows are you using? What type of shell are you using -- it looks like just a Command Prompt? If it is a Command Prompt, you may have to use "Edit" - "Paste" from the window menu in order to successfully paste the credentials.

**Comment by Dhyaan1** [comment]
Its Windows 11 and yes its the command Prompt( I tried this on powershell too, same problem)

The  _"Edit" - "Paste" from the window menu_ that you mentioned is probably a windows 10 thing
But i did find its windows 11 equivalent
Here,
![image](https://github.com/user-attachments/assets/b099fa19-257d-4fcb-b774-ff7a938637e8)
This does work for normal cases the same way CTRL + V works
But it still doesn't work for the password prompt.

https://github.com/user-attachments/assets/b1bca8e5-44cd-4de0-befa-b6e7553a0378

Same thing happens for the One-time code too as you can see in the original issue, i say yes, it opens a tab on my browser to show me a code, i copy the code, i cant do anything with the code.

The only issue i could find that was similar to this was [Here](https://github.com/cloud-annotations/cloud-annotations/issues/61), but they didn't solve the problem because they apparently never needed to log in(run ibmcloud login).


# To help reproduce this failure

**Context:** I started to use this software today while following an IBM course, i have never used IBM Cloud CLI ever before, this issue pretty much arose in the set-up stage for me.
This is the documentation my course linked me to
https://cloud.ibm.com/docs/cli?topic=cli-getting-started
which pointed me to the releases on [GitHub](https://github.com/IBM-Cloud/ibm-cloud-cli-release/releases/)

I downloaded the IBM Cloud CLI from here (The windows 64 bit version for the latest release)
https://download.clis.cloud.ibm.com/ibm-cloud-cli/2.27.0/IBM_Cloud_CLI_2.27.0_amd64.exe

## Possible point of failure 1: 

I used the releases on GitHub to install IBM Cloud CLI instead of simply doing the command that the page suggested for windows( I was hoping I'd get to chose the location of installation if I'd use the GitHub releases)
![image](https://github.com/user-attachments/assets/95096c4f-f0fd-4de3-977e-191682f8fb19)

---

Then according to my course i first ran the command
![image](https://github.com/user-attachments/assets/d89e3d65-3db8-4cbb-96d2-e6359ebfe26d)
which gave me this
![image](https://github.com/user-attachments/assets/0e3805a2-1d9c-44bd-9ed8-6a3acd8df84f)
Which i am assuming means that it works

My next task was to Install the Container Registry CLI [Docs](https://cloud.ibm.com/docs/Registry?topic=Registry-getting-started#gs_registry_cli_install)
![image](https://github.com/user-attachments/assets/f50437c0-e9cf-40ee-947e-78604f71a711)

Which also appears to have worked
``` bash
ibmcloud plugin list
``` 
![image](https://github.com/user-attachments/assets/b73b9c72-dd12-49f6-9ac1-29b5961e3d4a)

Now, for the task where it went wrong
![image](https://github.com/user-attachments/assets/e2147e56-c818-4e97-ba46-bb9a970ca65a)

As i have shown in my original Issue, any keys i click on the keyboard don't seems to do anything when the password or One-time code message shows up.

---

## Possible point of failure: 

Perhaps my IBM cloud account is not working as it should, the CLI has the same password prompt blocking issue when i use anything as an email. So, it maybe be blocking me off because it thinks my email is wrong?

![image](https://github.com/user-attachments/assets/af98ecd2-2a2f-45a2-afac-471e3f65b156)


Right before i was going to send this comment i noticed another behavior

Even though i am blocked from typing out my password, it does still detect when nothing was typed(Times when i didn't even try typing before clicking enter)
![image](https://github.com/user-attachments/assets/ab162dcf-931b-44d4-bced-e3f0ed2762a5)

But when i do type out something or do a CTRL + V
![image](https://github.com/user-attachments/assets/a2199f34-d682-4c6b-b181-0ed571fa9007)

As i mentioned in my original Issue, i did try and type out my actual password/One-time code several time even though i had no CLI response

I will keep trying this and update on this issue thread, i think i might be able to work around the "No CLI showing" issue

**Comment by Dhyaan1** [comment]
# Update: Got it working!!

Even though the One-Time code here is invisible, it is apparently there when you CTRL + V without trying to type out anything before hand (even if you type like 3 letters and then backspace, it will work).


![image](https://github.com/user-attachments/assets/ebee33fd-f7ee-47e1-8b81-0720e054a49b)


The Email and password method still doesn't work though.


# Conclusion

I think its because i may have a federated ID
![image](https://github.com/user-attachments/assets/f5376f66-0685-4d6b-9541-62cf7c0d0c63)

Which is why only the One-time code method works

Why the password and OTC prompts are invisible? i don't know.

The login works, so i am closing this Issue.

**Comment by steveclay** [comment]
You are correct, these credential prompts are hidden to avoid inadvertent disclosure. Also glad you were able to resolve the method of login for your account.
