### ISSUE TITLE
There are no Windows installers/binaries for release v2.28.1

### ISSUE THREAD

**Issue by gian1200** [IBM-Cloud/ibm-cloud-cli-release#214]
https://github.com/IBM-Cloud/ibm-cloud-cli-release/releases

### Error while running CLI:
```shell
New version 2.28.1 is available.
Change logs: https://github.com/IBM-Cloud/ibm-cloud-cli-release/releases/tag/v2.28.1
TIP: use 'C:\Program Files\IBM\Cloud\bin\ibmcloud.exe config --check-version=false' to disable update check.

Do you want to update? [y/N] > y

Installing version '2.28.1'...
Failed to upgrade CLI: No binary is available for your Windows AMD64 operating system.
```

**Comment by steveclay** [comment]
@gian1200 yes, as stated in the release notes for 2.28.1, there are not Windows drivers for this version. Sorry for the inconvenience. This is a temporary problem that is being addressed.

**Comment by steveclay** [comment]
Release 2.28.2 has been released and includes the Windows installer.
