### ISSUE TITLE
Critical vulnerability in ibmcloud cli

### ISSUE THREAD

**Issue by whitfiea** [IBM-Cloud/ibm-cloud-cli-release#215]
The following critical vulnerability is present in the latest ibmcloud cli release, can this be resolved:

- Critical [GHSA-v23v-6jw2-98fq ](https://github.com/moby/moby/security/advisories/GHSA-v23v-6jw2-98fq) found in github.com/docker/docker

**Comment by steveclay** [comment]
You should no longer find this concern with the 2.31.0 release:  https://github.com/IBM-Cloud/ibm-cloud-cli-release/releases/tag/v2.31.0 . Please let us know if there are any more concerns and thanks again.
