### ISSUE TITLE
Problems with resources groups when I destine a API terminal and Login to IBM  Cloud

### ISSUE THREAD

**Issue by rafaooliveira** [IBM-Cloud/ibm-cloud-cli-release#22]
I need add some resources group, cause I don't have none.

I try to find new group with these commands:

bx target -g RESOURCE_GROUP
bx target -o ORG -s SPACE
bx resource groups 

I can't add organization, space and resources. Someone can help me?

**Comment by boyang9527** [comment]
@rafaooliveira  can you please show me how you did  'bx login' ?  are you the owner of the account you selected?  Do you have permissions to create org, space in the account and permissions of the resource groups under the account?

**Comment by rafaooliveira** [comment]
of course, I used the tutorial to configure my cluster, but I thing that I did something wrong, cause my cluster is "mycluster-rafael", and when I will configure my cluster and I logging using

bx login

I see this screen:

![captura de tela de 2018-02-20 14-47-13](https://user-images.githubusercontent.com/33132254/36439891-f86af000-164c-11e8-85c3-34e64b231afe.png)

**Comment by rafaooliveira** [comment]
my terminal is in portuguese, sorry

**Comment by boyang9527** [comment]
from the login process,  looks like
1) you are not the owner of account 'IBM' and you don't have permission of resource group of that account 

2) 'bx target -o ORG' is not correct, you need to replace ORG with the org name you want to target
I would suggest you to run 'bx target --cf', this will allow you select the org / space interactively...

**Comment by rafaooliveira** [comment]
I tried to use this command, but a message appeared "no organization was found" 
When I login in IBM cloud I know that I have a cluster, do you know if I can access this cluster or configure it?

This is my cluster:

![captura de tela de 2018-02-20 15-01-50](https://user-images.githubusercontent.com/33132254/36440703-086286b0-164f-11e8-8d97-d08d7860f766.png)

**Comment by boyang9527** [comment]
so you are not invited to any org of the account. 

You can see the Kube cluster since it belongs to an account, not an org.  To manage the kube cluster, you will need to use "container-service" plugin.

```
bx plugin install container-service
```

use 
```
bx cs
```
to see the commands
