### ISSUE TITLE
bx dev build results in an infinite loop on mac os x

### ISSUE THREAD

**Issue by nlamot** [IBM-Cloud/ibm-cloud-cli-release#23]
Hi

I'm trying out the IBM Cloud cli to build a maven project and deploy it to IBM Cloud.
I just downloaded the sample web app from java starter in Web Apps and I'm following the steps of the tutorial.

When I try to run "bx dev build -trace", I see it falling into an infinite loop after this step:
 ---> 2b7c109ba259
Step 8/8 : RUN if [ $bx_dev_user != "root" ]; then useradd -ms /bin/bash -u $bx_dev_userid $bx_dev_user; fi

 ---> Running in e85cd4682137

This seems to continue until my disk space runs out. He keeps generating something (probably some kind of log) until my disk is out of space and it fails.

Is this a known issue? I tried reinstalling the cli, reinstalling docker, but the same issue keeps on happening. A colleague of mine tried it on Ubuntu with the same code, but there was no issue there.
The same thing also happens when I try a node js project.

Kind regards
Nils

**Comment by boyang9527** [comment]
thanks for reporting this.  I am forwarding to the right contact to help.

**Comment by triceam** [comment]
Hi @nlamot, thanks for reporting this.  Can you provide a little bit more information so we can try to isolate the issue that you're seeing?

* What operating system are you using?  
* Did you create this project using the cli, or through the web interface?   If created by the CLI, you would have used the `bx dev create` command.  If created through the web interface, you would have had to follow the UI wizard, and then downloaded a zip file.
* What version of `bx` cli are you using?  You can get this by running `bx --version` on the command line.
* What version of the `dev` extension are you using?  You can get this by running `bx plugin list` on the command line.
* What version of Docker are you using?  Get this by running `docker --version`.
* Just to confirm, you are seeing this with the `Web App - Java MicroProfile / Java EE Basic` starter, right?
* Also, how did you reinstall the CLI?  Did you use the installation script in the [instructions here](https://console.bluemix.net/docs/cloudnative/idt/index.html), or manually download and install?  

You could try clearing out your Docker image/container cache and rebuild.  Here's a shell script that will remove ***all*** docker images and containers, so be careful with it:

```
#!/bin/bash
read -p "Delete all Docker images/containers? " -n 1 -r
echo    # (optional) move to a new line

if [[ $REPLY =~ ^[Yy]$ ]]
then
    # Delete all containers
    docker rm $(docker ps -a -q)
    # Delete all images
    docker rmi $(docker images -q)
fi
```

**Comment by nlamot** [comment]
Hi triceam

Thanks for your quick response!

- Operating System: macOS High Sierra (10.13.3)
- I created projects both with CLI and through web interface. In both cases, I ended up with the same problem.
- bx version 0.6.5+0183260a-2018-02-05T08:42:03+00:00
- dev 1.1.4
- Docker version 17.12.0-ce, build c97c6d6
- I'm seeing this with Java Spring Basic, but also with Express.js backend. I'm assuming I'll see this with every starter.
- I did reinstall cli and docker, but both didn't solve the problem.
- I also tried clearing out docker image/container cache and rebuild, but this also didn't solve my problem.

Kind regards
Nils

**Comment by boyang9527** [comment]
@triceam  is this fixed ?

**Comment by triceam** [comment]
@boyang9527 Nobody on our team has been able to recreate it yet... are you seeing this also?

**Comment by steveclay** [comment]
@nlamot in `Dockerfile-tools`, could you comment out the line that looks like this:

`RUN BX_DEV_USER=$bx_dev_user`

Then rerun and see what result you get?  This should prevent trying to add your user into the tools container, if that is what is causing the hang.

Thanks

**Comment by boyang9527** [comment]
it has been some time since I did it last time. I gave a try just right now, I can not reproduce the issue either.

**Comment by nlamot** [comment]
Hi @steveclay

I tried commenting out the line. In that case, my build doesn’t hang, but I get the following error message:
unable to find user nils.lamot: no matching entries in passwd file

So it seams like it’s indeed linked to adding my user.

Kind regards
Nils

**Comment by nlamot** [comment]
I'm sorry, I deleted this line, instead of the one you specified:
RUN if [ $bx_dev_user != "root" ]; then useradd -ms /bin/bash -u $bx_dev_userid $bx_dev_user; fi

When I remove the one you specified, it still gets into an infinite loop.

Kind regards
Nils

**Comment by steveclay** [comment]
@nlamot 

My MacOS is High Sierra 10.13.2 (slightly older)
Docker version 17.12.0-ce, build c97c6d6 (same)
bx version 0.6.5+0183260a-2018-02-05T08:42:03+00:00 (same)
dev version 1.1.4 (same) and 1.2.0 (released yesterday)

Unfortunately, I'm still unable to reproduce the problem.  Would you mind trying this from the folder for your app ...

`docker build . -f Dockerfile-tools` (see if this goes to completion)

If the above is successful, then retry `bx dev build --trace`

Thanks

**Comment by nlamot** [comment]
Hi @steveclay 

Thanks for your help!
I tried building with docker first using your command and this finished correctly.
However, when trying bx dev build --trace again, the same error occurs.
I'm beginning to think my machine is haunted :).

In the mean time, I'm working directly with docker and kubernetes command. This seems to work.

Kind regards
Nils

**Comment by triceam** [comment]
@nlamot can you look at the contents of your project's `cli-config.yml` file, and confirm the `version` that was generated?   It should be `version : "0.0.3"`.   That will help us track down how this might occur.

**Comment by nlamot** [comment]
@triceam, my version is indeed 0.0.3.

**Comment by patbduarte** [comment]
I had same issue on Red Hat 7, you can only reproduce it if your user id is 1000. Seems it tries to add your user (from passwd file) and it fails cuz the docker image already has an user with id=1000 (root). Change to any other user and it works!
