### ISSUE TITLE
mac OS x64 installer fails on macOS 10.12.16

### ISSUE THREAD

**Issue by jshortl** [IBM-Cloud/ibm-cloud-cli-release#24]
I have a MacBook Pro and downloaded the IBM CLI 64-bit installer; have 468 mb of disk and the installer failed. I have an Intel Core i5 64-bit processor, level of OS is macOS 10.12.6 (16G29).

thanks

**Comment by boyang9527** [comment]
what is the failure message?  we only need tens of MegaBytes

**Comment by jshortl** [comment]
Hi I got a popup that stated the cli failed to install, contact my provider. It went up to writing the files, then no specific error message, here is a capture of the message: 
![cli_2](https://user-images.githubusercontent.com/36714590/36547579-30aad910-17bc-11e8-8cab-665edfe5d36b.jpeg)

**Comment by boyang9527** [comment]
@archerzz  do you have any ideas on this?

**Comment by nuetz** [comment]
Same issue for me.

**Comment by jshortl** [comment]
is there any update on this???

thanks

**Comment by dden** [comment]
same issue is happening in some case on MacOS High Sierra version 10.13.3.
I have tried 3 different versions: 0.6.6, 0.6.5, 0.6.4. They all fail installation. No particular message: just contact software provider. 

any update?

thanks

**Comment by jimpiety** [comment]
I'm having the same issue as everyone. What to do...what to do...

**Comment by boyang9527** [comment]
@jshortl  @nuetz @jimpiety  please create directory /usr/local/bin if it does not exist and try again.
