### ISSUE TITLE
Service API calls timeout

### ISSUE THREAD

**Issue by xikaos** [IBM-Cloud/ibm-cloud-cli-release#25]
Hi there!

I'm experiencing some problems when running commands related to services such as `bx service offerings` or `bx service create` calls.

Since I'm using the CLI for the Bluemix Essentials Devworks course, I don't know how to test other verbs or actions related to services.

I'm not using a HTTP proxy or setting up specific firewall rules.

I've pasted the terminal session since login in this link: https://pastebin.com/i4b72xVi

I don't know if it is a network issue or some sort of instability. Hope you guys can help me!

Thanks in advance!

**Comment by xikaos** [comment]
It seems it was a network issue. Worked perfectly under new network conditions. 
Issue closed.

**Comment by boyang9527** [comment]
thanks for the update, closing the issue.
