### ISSUE TITLE
cf login - Credentials were rejected, please try again.

### ISSUE THREAD

**Issue by HenryUxDesugner** [IBM-Cloud/ibm-cloud-cli-release#27]
I am trying to use api key for cf login as instructed in the following link. But I am getting error **Credentials were rejected, please try again**, but I am able to login with same api key using bluemix login. 

Can you guys please help?

https://console.bluemix.net/docs/iam/login_fedid.html#using-an-api-key

**Comment by boyang9527** [comment]
please post how you use it and what you got

**Comment by fabio-franco** [comment]
I am having same issue. I am a IBM employee and only way I found here to login there is always using sso option. I downloaded and installed IBM Cloud Cli (https://console.bluemix.net/docs/cli/reference/bluemix_cli/get_started.html#getting-started) I have tried to login using "bx login" and also tried using "bluemix login" so I get message "Credentials were rejected. Code: BXNIM0608E, message: Your user id 'myuser@ibm.com' is federated and must use an API key or one-time passcode to authenticate". So I searched getting started links and found nothing. However, searching on internet I found that sso option as described here (https://console.bluemix.net/docs/iam/login_fedid.html#using-an-api-key), that is, "bluemix login --sso" and after that entered on page indicated to get key: One Time Code (Get one at https://iam-id-2.ng.bluemix.net/identity/passcode). So, always that I need to login on terminal only way it works is by using this sso option and entering on that link to get new key. I was wondering it has an easier and direct way to do that and also I was wondering that bluemix documentation was better explanning how this works direct on getting started site (https://console.bluemix.net/docs/cli/reference/bluemix_cli/get_started.html#getting-started).

**Comment by boyang9527** [comment]
@fabio-franco  have you ever created a platform api key after you login with --sso. After you have the api key, you will be always using the API key to login  as described in the document

bluemix login --apikey <api_key_string>

**Comment by boyang9527** [comment]
@HenryUxDesugner  when you use cf cli to login, what you input for "EMAIL:" ?  it needs to be `apikey` ( exactly this string)

**Comment by TheDeployGuy** [comment]
Just to comment on the issue:

```
➜ ibmcloud login
API endpoint: https://api.eu-gb.bluemix.net

Email> apikey

Password>
Authenticating...
Credentials were rejected.
Code: BXNIM0602E, message: The credentials you entered for the user 'apikey' are incorrect
```

If i use same API key with the command line argument it works:
```
ibmcloud login --apikey $API_KEY
API endpoint: https://api.eu-gb.bluemix.net
Authenticating...
OK
```

It does not like when you have email as 'apikey'

**Comment by boyang9527** [comment]
use "apikey" as email and key as password is only for cf cli.  
For IBM Cloud CLI, you need to use --api-key option

**Comment by mahesh2000** [comment]
i ran ibmcloud login and while it failed logging in, it did update itself. after this, i've been able to login both via ibmcloud and via cf using email & password. i couldn't get the apikey thing to work.
