### ISSUE TITLE
Error when downloading v0.6.6 installer

### ISSUE THREAD

**Issue by arewm** [IBM-Cloud/ibm-cloud-cli-release#30]
When trying to download the platform-specific installer version, I get the message:

```
Unknown version : 0.6.6
```
<img width="811" alt="unrecognizedversion" src="https://user-images.githubusercontent.com/16674323/37658632-63b012e0-2c24-11e8-8fbc-c8f531063b42.png">

*Note: Downloading the assets succeeds (.zip/.tar.gz)*

**Comment by boyang9527** [comment]
v0.6.6 at that time was not available yet...  Do you have the issue now?

**Comment by arewm** [comment]
No, it works now. I thought that v0.6.6 might have been available since the .zip/.tar.gz downloads worked. 

Thanks.
