### ISSUE TITLE
Seems that IBM cloud cli can not be used on Linux® on Power® 64-bit LE machine

### ISSUE THREAD

**Issue by githubzwk** [IBM-Cloud/ibm-cloud-cli-release#32]
Hi,
I am installing IBM cloud cli on a Linux® on Power® 64-bit LE server. Seem there is a problem in this case.

1. When try to Install from the shell with below command and it gives below result.
[root@helper211 ~]# curl -fsSL https://clis.ng.bluemix.net/install/linux | sh
Unsupported Linux architecture: ppc64le. Quit installation.

2. With Use installer way, installation process can be finished successfully, but can not run cli command like below.
[root@helper21 ~]# bluemix
-bash: /usr/local/bin/bluemix: cannot execute binary file
[root@helper21 ~]# bx
-bash: /usr/local/bin/bx: cannot execute binary file

Any idea or any suggestion? Can the server OS not be supported?

**Comment by boyang9527** [comment]
power linux support is coming from next release v0.6.7
