### ISSUE TITLE
No platform recognition when installing linux version

### ISSUE THREAD

**Issue by jamesgua** [IBM-Cloud/ibm-cloud-cli-release#33]
Tried to install [linux 64](https://clis.ng.bluemix.net/download/bluemix-cli/latest/linux64), extract and run script to finish installation:
`Copying files ...
IBM Cloud Command Line Interface(IBM Cloud CLI) is installed successfully.
To get started, open a terminal window and enter "bluemix help".

IBM Cloud CLI has plug-in framework to extend its capability. Go to https://console.bluemix.net/docs/cli/reference/bluemix_cli/extend_cli.html for how to install plug-ins.

IBM Cloud CLI automatically collects data for usage analysis and use experience improvement. No personally identifiable data is collected.
To disable the collecting,  run:
        "bluemix config --usage-stats-collect false"`

However, file format is for x86_64 only, so it won't work on other platforms like s390x or ppc64le. It's misleading and not precise, user would assume that the package can be adapted to Linux-s390x and Linux-ppc64le as well.

At least the installation should fail with "unsupported platform" or similar info.

**Comment by boyang9527** [comment]
thanks for reporting this. Will add platform check in installer for linux. 

Now we only support x86 for linux, the ppc64le is coming soon.  There is linux s390 installer on download server https://public.dhe.ibm.com/cloud/bluemix/cli/bluemix-cli/0.6.6/, but no formal support.

**Comment by boyang9527** [comment]
it should be added.
