### ISSUE TITLE
billing org-usage fails due to wrong region

### ISSUE THREAD

**Issue by OlivierJacques** [IBM-Cloud/ibm-cloud-cli-release#34]
I'm using the master account to retrieve billing information with CLI commands.
I have no issue with **bx billing account-usage** but **bx billing org-usage ORGNAME** which fails with the following:
Retrieving usage for org ORGNAME...
FAILED
Could not get usage data for org 'ORGNAME' in region 'us-south'.Error: Error response from server. Status code: 500; description: error: {code: v4_abacus_reporting_query_error, message: Unable to query v4 abacus reporting for reports}.

bx target gives the following:

API endpoint: https://api.eu-gb.bluemix.net (API version: 2.92.0)
Region: eu-gb
User: xxxxxxxx@xx.ibm.com
Account: xxxxxxxxx (xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx) <-> xxxxxxxx
Resource group: Default
Org: ORGNAME
Space: accp

It looks like billing org-usage search in the region us-south by default but I have no way to tell the command to search in the eu-gb region.
From the documentation there is no way to specify the region.

Thank you in advance to look at this issue.

**Comment by boyang9527** [comment]
please enable trace and see what happens 

BLUEMIX_TRACE=true bx billing org-usage  xxx

**Comment by OlivierJacques** [comment]
Hi Bo,
Thank you for the quick reply.
See as attachment the trace you were asking for: (See attached file:
billing org-usage fails due to wrong region #34 - trace.txt)

I hope this will help you to figure out that happens.


Met vriendelijke groet, Kind regards, Cordialement

Olivier Jacques
Integration Architect
IT Strategy & Design, IBM Global Technology Services
                                                                       
                                                                       
                                                                       
                                                                       
                                                                       
              Mobile: +31(0)6 5159 0505                                
              Phone: +31(0)20 513 6257                                 
              E-mail: olivier_jacques@nl.ibm.com   J. Huizingalaan 765 
              Web: www.ibm.com/services/nl          Amsterdam, 1066 VH 
              Find me on:                                  Netherlands 
                                                                       


IBM Nederland B.V. Gevestigd te Amsterdam Inschrijving Handelsregister
Amsterdam Nr. 33054214



From:	Bo Yang <notifications@github.com>
To:	IBM-Cloud/ibm-cloud-cli-release
            <ibm-cloud-cli-release@noreply.github.com>
Cc:	OlivierJacques <Olivier_jacques@nl.ibm.com>, Author
            <author@noreply.github.com>
Date:	05/04/2018 18:04
Subject:	Re: [IBM-Cloud/ibm-cloud-cli-release] billing org-usage fails
            due to wrong region (#34)





please enable trace and see what happens


BLUEMIX_TRACE=true bx billing org-usage xxx


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.




Tenzij hierboven anders aangegeven: / Unless stated otherwise above:
IBM Nederland B.V.
Gevestigd te Amsterdam
Inschrijving Handelsregister Amsterdam Nr. 33054214

FAILED
Incorrect Usage.

REQUEST: [2018-04-06T08:33:54+02:00]
GET /v2/organizations?q=name%3AHydroMeteo&region=all HTTP/1.1
Host: mccp.eu-gb.bluemix.net
Accept: application/json
Accept-Language: en_US
Accept-Language: en
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: IBM Cloud CLI 0.6.6 / windows



RESPONSE: [2018-04-06T08:33:55+02:00] Elapsed: 580ms
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Access-Control-Allow-Headers: Content-Type
Access-Control-Allow-Methods: GET,OPTIONS,POST,DELETE,PUT,PATCH
Access-Control-Allow-Origin: undefined
Connection: Keep-Alive
Content-Type: application/json; charset=utf-8
Date: Fri, 06 Apr 2018 06:33:55 GMT
Etag: W/"11e8-CmyXwW9RAOP8bSjS0SZHhjaTQ6M"
X-Backside-Transport: OK OK
X-Global-Transaction-Id: 1786854919
X-Ratelimit-Limit: 750
X-Ratelimit-Remaining: 747
X-Ratelimit-Reset: 1522996435406
X-Response-Time: 404.788

11e8
{
  "total_results": 3,
  "total_pages": 1,
  "prev_url": null,
  "next_url": null,
  "resources": [
    {
      "metadata": {
        "guid": "2ac382ee-42ec-435d-9c22-bc08128e3a3d",
        "url": "/v2/organizations/2ac382ee-42ec-435d-9c22-bc08128e3a3d",
        "created_at": "2017-10-20T10:45:21Z",
        "updated_at": "2018-01-09T13:40:26Z"
      },
      "entity": {
        "name": "HydroMeteo",
        "billing_enabled": false,
        "quota_definition_guid": "18c11c06-82f6-4caa-9ecc-0766758d17e5",
        "status": "active",
        "default_isolation_segment_guid": null,
        "quota_definition_url": "/v2/quota_definitions/18c11c06-82f6-4caa-9ecc-0766758d17e5",
        "spaces_url": "/v2/organizations/2ac382ee-42ec-435d-9c22-bc08128e3a3d/spaces",
        "domains_url": "/v2/organizations/2ac382ee-42ec-435d-9c22-bc08128e3a3d/domains",
        "private_domains_url": "/v2/organizations/2ac382ee-42ec-435d-9c22-bc08128e3a3d/private_domains",
        "users_url": "/v2/organizations/2ac382ee-42ec-435d-9c22-bc08128e3a3d/users",
        "managers_url": "/v2/organizations/2ac382ee-42ec-435d-9c22-bc08128e3a3d/managers",
        "billing_managers_url": "/v2/organizations/2ac382ee-42ec-435d-9c22-bc08128e3a3d/billing_managers",
        "auditors_url": "/v2/organizations/2ac382ee-42ec-435d-9c22-bc08128e3a3d/auditors",
        "app_events_url": "/v2/organizations/2ac382ee-42ec-435d-9c22-bc08128e3a3d/app_events",
        "space_quota_definitions_url": "/v2/organizations/2ac382ee-42ec-435d-9c22-bc08128e3a3d/space_quota_definitions",
        "region": "eu-gb"
      }
    },
    {
      "metadata": {
        "guid": "f335963d-0b23-4795-ba78-65b89b149601",
        "url": "/v2/organizations/f335963d-0b23-4795-ba78-65b89b149601",
        "created_at": "2017-11-14T08:01:06Z",
        "updated_at": "2017-11-14T08:01:06Z"
      },
      "entity": {
        "name": "HydroMeteo",
        "billing_enabled": false,
        "quota_definition_guid": "1fdfd52b-634f-4af3-87c4-176923ecb37c",
        "status": "active",
        "default_isolation_segment_guid": null,
        "quota_definition_url": "/v2/quota_definitions/1fdfd52b-634f-4af3-87c4-176923ecb37c",
        "spaces_url": "/v2/organizations/f335963d-0b23-4795-ba78-65b89b149601/spaces",
        "domains_url": "/v2/organizations/f335963d-0b23-4795-ba78-65b89b149601/domains",
        "private_domains_url": "/v2/organizations/f335963d-0b23-4795-ba78-65b89b149601/private_domains",
        "users_url": "/v2/organizations/f335963d-0b23-4795-ba78-65b89b149601/users",
        "managers_url": "/v2/organizations/f335963d-0b23-4795-ba78-65b89b149601/managers",
        "billing_managers_url": "/v2/organizations/f335963d-0b23-4795-ba78-65b89b149601/billing_managers",
        "auditors_url": "/v2/organizations/f335963d-0b23-4795-ba78-65b89b149601/auditors",
        "app_events_url": "/v2/organizations/f335963d-0b23-4795-ba78-65b89b149601/app_events",
        "space_quota_definitions_url": "/v2/organizations/f335963d-0b23-4795-ba78-65b89b149601/space_quota_definitions",
        "region": "eu-de"
      }
    },
    {
      "metadata": {
        "guid": "89c783d4-50e7-48fa-8279-f54e45b53208",
        "url": "/v2/organizations/89c783d4-50e7-48fa-8279-f54e45b53208",
        "created_at": "2017-10-23T09:10:28Z",
        "updated_at": "2017-11-07T11:50:03Z"
      },
      "entity": {
        "name": "HydroMeteo",
        "billing_enabled": false,
        "quota_definition_guid": "ee8bf3cc-8776-4300-a490-b17552723c14",
        "status": "active",
        "default_isolation_segment_guid": null,
        "quota_definition_url": "/v2/quota_definitions/ee8bf3cc-8776-4300-a490-b17552723c14",
        "spaces_url": "/v2/organizations/89c783d4-50e7-48fa-8279-f54e45b53208/spaces",
        "domains_url": "/v2/organizations/89c783d4-50e7-48fa-8279-f54e45b53208/domains",
        "private_domains_url": "/v2/organizations/89c783d4-50e7-48fa-8279-f54e45b53208/private_domains",
        "users_url": "/v2/organizations/89c783d4-50e7-48fa-8279-f54e45b53208/users",
        "managers_url": "/v2/organizations/89c783d4-50e7-48fa-8279-f54e45b53208/managers",
        "billing_managers_url": "/v2/organizations/89c783d4-50e7-48fa-8279-f54e45b53208/billing_managers",
        "auditors_url": "/v2/organizations/89c783d4-50e7-48fa-8279-f54e45b53208/auditors",
        "app_events_url": "/v2/organizations/89c783d4-50e7-48fa-8279-f54e45b53208/app_events",
        "space_quota_definitions_url": "/v2/organizations/89c783d4-50e7-48fa-8279-f54e45b53208/space_quota_definitions",
        "region": "us-south"
      }
    }
  ]
}
0



REQUEST: [2018-04-06T08:33:55+02:00]
POST /coe/v2/getaccounts HTTP/1.1
Host: accountmanagement.bluemix.net
Accept: application/json
Accept-Language: en_US
Accept-Language: en
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: IBM Cloud CLI 0.6.6 / windows

{"organizations_region":[{"guid":"2ac382ee-42ec-435d-9c22-bc08128e3a3d","region":"eu-gb"}]}

RESPONSE: [2018-04-06T08:33:55+02:00] Elapsed: 476ms
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Access-Control-Allow-Headers: Content-Type
Access-Control-Allow-Methods: GET,OPTIONS,POST,DELETE,PUT,PATCH
Access-Control-Allow-Origin: undefined
Cache-Control: no-cache, no-store, must-revalidate
Connection: keep-alive
Content-Type: application/json
Date: Fri, 06 Apr 2018 06:33:56 GMT
Expires: 0
Pragma: no-cache
Transaction-Id: 20153552172
Vary: X-HTTP-Method-Override, Accept-Encoding
X-Powered-By: Express
X-Request-Id: 20153552172
X-Response-Time: 372.531ms
_request_id: 20153552172

b8e
{
  "total_results": 1,
  "resources": [
    {
      "metadata": {
        "guid": "b87803451a162963d8bb5a1adb1b16c8",
        "url": "/coe/v2/accounts/b87803451a162963d8bb5a1adb1b16c8",
        "created_at": "2017-10-20T06:11:06.677Z",
        "updated_at": "2018-02-14T02:39:56.607Z"
      },
      "entity": {
        "name": "GBS c/o Port of Rotterdam",
        "type": "SUBSCRIPTION",
        "state": "ACTIVE",
        "owner": "bf4c449f-0a74-4680-bb67-31deb3dc5d61",
        "owner_userid": "portofrotterdam@nl.ibm.com",
        "owner_unique_id": "5040S5X6B9",
        "customer_id": "b87803451a162963d8bb5a1adb1b16c8",
        "country_code": "NLD",
        "currency_code": "EUR",
        "billing_country_code": "NLD",
        "terms_and_conditions": {
          "required": true,
          "accepted": true,
          "timestamp": "2017-10-20T06:11:06.677Z"
        },
        "tags": [],
        "team_directory_enabled": true,
        "organizations_region": [
          {
            "guid": "2ac382ee-42ec-435d-9c22-bc08128e3a3d",
            "region": "eu-gb"
          },
          {
            "guid": "89c783d4-50e7-48fa-8279-f54e45b53208",
            "region": "us-south"
          },
          {
            "guid": "f335963d-0b23-4795-ba78-65b89b149601",
            "region": "eu-de"
          }
        ],
        "linkages": [
          {
            "origin": "IMS",
            "state": "COMPLETE"
          }
        ],
        "charge_agreement_number": "0077226991",
        "partner_customer_number": "0003960587",
        "bluemix_subscriptions": [
          {
            "type": "SUBSCRIPTION",
            "state": "ACTIVE",
            "payment_method": {
              "type": "PURCHASE_ORDER",
              "started": "2017-11-06T18:41:56.000Z",
              "ended": "2022-11-06T18:41:55.999Z"
            },
            "subscription_id": "49J283ZROXJGIFLOHGSW",
            "part_number": "D1U0YLL",
            "line_item_id": 10,
            "subscriptionTags": [],
            "history": [
              {
                "type": "TRIAL",
                "state": "ACTIVE",
                "startTime": "2017-10-20T06:11:06.677Z",
                "endTime": "2017-11-07T11:50:02.599Z",
                "billing_system": "DSW"
              }
            ],
            "current_state_timestamp": "2017-11-07T11:50:02.600Z",
            "subscription_amount": 4989,
            "term": "12",
            "billing_frequency": "A",
            "configuration_id": "5737E4320171102",
            "renewalModeCode": "O",
            "sales_doc_type_code": "ZSSA",
            "softlayer_account_id": 1500571,
            "billing_system": "DSW",
            "charge_agreement_number": "0077226991",
            "partner_customer_number": "0003960587"
          }
        ],
        "subscription_id": "49J283ZROXJGIFLOHGSW",
        "configuration_id": "5737E4320171102",
        "onboarded": 0
      }
    }
  ]
}
0



REQUEST: [2018-04-06T08:33:55+02:00]
GET /v4/accounts/b87803451a162963d8bb5a1adb1b16c8/organizations/eu-gb:2ac382ee-42ec-435d-9c22-bc08128e3a3d/usage/2018-04?_names=true HTTP/1.1
Host: metering-reporting.eu-gb.bluemix.net
Accept: application/json
Accept-Language: en_US
Accept-Language: en
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: IBM Cloud CLI 0.6.6 / windows



RESPONSE: [2018-04-06T08:33:56+02:00] Elapsed: 1027ms
HTTP/1.1 200 OK
Content-Length: 7992
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Fri, 06 Apr 2018 06:33:57 GMT
Etag: W/"1f38-6aFMqOfUs8lpgTmM0fV+5+fQYIY"
Vary: Accept-Encoding
X-App-Index: 0
X-App-Name: metering-reporting
X-App-Version: 4.0.0
X-Heap-Used: 45384096
X-Instance-Id: 41
X-Instance-Index: 0
X-Node-Version: v6.13.0
X-Powered-By: Express
X-Process-Id: 41
X-Response-Time: 890.995
X-Uptime: 2029714.47

{"pricing_country":"EURO","currency_code":"EUR","billing_country":"NLD","resources":[{"resource_id":"5acdbc42-8965-48f9-8a3c-1c728b6ed2c4","billable_cost":748.4069999999999,"non_billable_cost":0,"plans":[{"plan_id":"7f19407b-f9fd-4e74-8c75-3355eee89628","billable":true,"pricing_plan_id":"billable:v4:7f19407b-f9fd-4e74-8c75-3355eee89628::1509494400000:","cost":748.4069999999999,"usage":[{"metric":"INSTANCES_PER_MONTH","unit":"INSTANCE","price":[],"quantity":3,"rateable_quantity":3,"cost":0},{"metric":"HOSTS_HOURS_PER_MONTH","unit":"HOUR","price":[{"unitQuantity":"1","tier_model":"Granular Tier","price":1.98,"quantity_tier":"1"}],"quantity":377.9833333333333,"rateable_quantity":377.9833333333333,"cost":748.4069999999999}],"plan_name":"Standard Hourly"}],"resource_name":"Streaming Analytics"},{"resource_id":"liberty-for-java","billable_cost":71.56639234575,"non_billable_cost":0,"plans":[{"plan_id":"04082014.ibm.liberty.default","billable":true,"pricing_plan_id":"billable:v4:04082014.ibm.liberty.default::1404057600000:","cost":71.56639234575,"usage":[{"metric":"GB_HOURS_PER_MONTH","unit":"GB-HOURS","price":[{"unitQuantity":"100","tier_model":"Granular Tier","price":5.26,"quantity_tier":"1"}],"quantity":1360.57780125,"rateable_quantity":1360.57780125,"cost":71.56639234575}],"plan_name":"Default"}],"resource_name":"IBM Bluemix Liberty for Java"},{"resource_id":"platform-a495-4aa1-9ef9-40b88a42d776","billable_cost":73.23063649655555,"non_billable_cost":0,"plans":[{"plan_id":"04082014.ibm.platform.default","billable":true,"pricing_plan_id":"billable:v4:04082014.ibm.platform.default::1404057600000:","cost":73.23063649655555,"usage":[{"metric":"GB_HOURS_PER_MONTH","unit":"GB-HOURS","price":[{"unitQuantity":"100","tier_model":"Granular Tier","price":5.26,"quantity_tier":"1"}],"quantity":1392.2174238888888,"rateable_quantity":1392.2174238888888,"cost":73.23063649655555}],"plan_name":"Default"}],"resource_name":"IBM Bluemix Platform Runtime"},{"resource_id":"sdk-for-nodejs","billable_cost":1.6643391230277778,"non_billable_cost":0,"plans":[{"plan_id":"04082014.ibm.node.default","billable":true,"pricing_plan_id":"billable:v4:04082014.ibm.node.default::1404057600000:","cost":1.6643391230277778,"usage":[{"metric":"GB_HOURS_PER_MONTH","unit":"GB-HOURS","price":[{"unitQuantity":"100","tier_model":"Granular Tier","price":5.26,"quantity_tier":"1"}],"quantity":31.641428194444444,"rateable_quantity":31.641428194444444,"cost":1.6643391230277778}],"plan_name":"Default"}],"resource_name":"IBM Bluemix Node.js"},{"resource_id":"6a7f4e38-f218-48ef-9dd2-df408747568e","billable_cost":15.3408,"non_billable_cost":0,"plans":[{"plan_id":"ibm.message.hub.standard_v1000","billable":true,"pricing_plan_id":"billable:v4:ibm.message.hub.standard_v1000::1449244800000:","cost":15.3408,"usage":[{"metric":"MESSAGES_PER_MONTH","unit":"MESSAGE","price":[{"unitQuantity":"100","tier_model":"Step Tier","price":2.26,"quantity_tier":"17000000"},{"unitQuantity":"100","tier_model":"Step Tier","price":7.52,"quantity_tier":"2000000"},{"unitQuantity":"100","tier_model":"Step Tier","price":3.76,"quantity_tier":"7000000"},{"unitQuantity":"100","tier_model":"Step Tier","price":1.28,"quantity_tier":"999999999"}],"quantity":3346511,"rateable_quantity":4000000,"cost":0.3008},{"metric":"PARTITIONS_PER_MONTH","unit":"PARTITION","price":[{"unitQuantity":"1","tier_model":"Granular Tier","price":7.52,"quantity_tier":"1"}],"quantity":10,"rateable_quantity":10,"cost":15.04}],"plan_name":"Standard"}],"resource_name":"Message Hub"},{"resource_id":"AlertNotification-8d3cff7f-bb94-1444678145000","billable_cost":128.63,"non_billable_cost":0,"plans":[{"plan_id":"a59608c8-493d-453d-a496-1145503408a8","billable":true,"pricing_plan_id":"billable:v4:a59608c8-493d-453d-a496-1145503408a8::1455552000000:","cost":128.63,"usage":[{"metric":"EMAIL_COUNT_PER_MONTH","unit":"EMAIL_COUNT","price":[],"quantity":0,"rateable_quantity":0,"cost":0},{"metric":"SMSMESSAGES_COUNT_PER_MONTH","unit":"SMSMESSAGE_COUNT","price":[],"quantity":0,"rateable_quantity":0,"cost":0},{"metric":"VOICECALLS_COUNT_PER_MONTH","unit":"VOICECALL_COUNT","price":[],"quantity":0,"rateable_quantity":0,"cost":0},{"metric":"MAXUSERS_PER_MONTH","unit":"MAXUSER_COUNT","price":[{"unitQuantity":"1","tier_model":"Granular Tier","price":6.77,"quantity_tier":"1"}],"quantity":19,"rateable_quantity":19,"cost":128.63}],"plan_name":"Authorized Users"}],"resource_name":"IBM Alert Notification"},{"resource_id":"cloudant","billable_cost":38.876969392,"non_billable_cost":0,"plans":[{"plan_id":"cloudant-standard","billable":true,"pricing_plan_id":"billable:v4:cloudant-standard::1490943600000:","cost":38.876969392,"usage":[{"metric":"LOOKUPS_PER_MONTH","unit":"LOOKUP","price":[{"unitQuantity":"100","tier_model":"Step Tier","price":18.8,"quantity_tier":"1"}],"quantity":67.76,"rateable_quantity":67.76,"cost":12.73888},{"metric":"WRITES_PER_MONTH","unit":"WRITE","price":[{"unitQuantity":"100","tier_model":"Step Tier","price":37.61,"quantity_tier":"1"}],"quantity":33.88,"rateable_quantity":33.88,"cost":12.742268},{"metric":"QUERIES_PER_MONTH","unit":"QUERY","price":[{"unitQuantity":"100","tier_model":"Step Tier","price":376,"quantity_tier":"1"}],"quantity":3.388,"rateable_quantity":3.388,"cost":12.73888},{"metric":"STORAGE_MANAGED_PER_MONTH","unit":"GIGABYTE","price":[{"unitQuantity":"100","tier_model":"Step Tier","price":75.22,"quantity_tier":"1"}],"quantity":0.8733600000000001,"rateable_quantity":0.8733600000000001,"cost":0.6569413920000001}],"plan_name":"Standard"}],"resource_name":"Cloudant NoSQL DB"},{"resource_id":"59b735ee-5938-4ebd-a6b2-541aef2d1f68","billable_cost":0,"non_billable_cost":0,"plans":[{"plan_id":"a35fb0e9-4fc2-400e-8161-49078e5af632","billable":true,"pricing_plan_id":"billable:v4:a35fb0e9-4fc2-400e-8161-49078e5af632::1483228800000:","cost":0,"usage":[{"metric":"AUTHORIZED_USERS_PER_MONTH","unit":"Authorized User","price":[],"quantity":39,"rateable_quantity":39,"cost":0},{"metric":"JOB_EXECUTIONS_PER_MONTH","unit":"Job Execution","price":[],"quantity":0,"rateable_quantity":0,"cost":0}],"plan_name":"Lite"}],"resource_name":"Continuous Delivery"},{"resource_id":"dashdb-for-transactions","billable_cost":183.74,"non_billable_cost":0,"plans":[{"plan_id":"dashDBTxFlex","billable":true,"pricing_plan_id":"billable:v4:dashDBTxFlex::1489680000000:","cost":183.74,"usage":[{"metric":"INSTANCES_PER_MONTH","unit":"INSTANCE","price":[{"unitQuantity":"1","tier_model":"Granular Tier","price":142,"quantity_tier":"1"}],"quantity":5,"rateable_quantity":5,"cost":142},{"metric":"HA_INSTANCES_PER_MONTH","unit":"HA_INSTANCE","price":[{"unitQuantity":"1","tier_model":"Granular Tier","price":142,"quantity_tier":"1"}],"quantity":1,"rateable_quantity":1,"cost":28.4},{"metric":"RAMS_PER_MONTH","unit":"GIGABYTE","price":[{"unitQuantity":"1","tier_model":"Granular Tier","price":9.78,"quantity_tier":"1"}],"quantity":26.666666666666668,"rateable_quantity":6.666666666666667,"cost":13.04},{"metric":"STORAGES_PER_MONTH","unit":"GIGABYTE","price":[{"unitQuantity":"1","tier_model":"Granular Tier","price":0.75,"quantity_tier":"1"}],"quantity":12,"rateable_quantity":2,"cost":0.3},{"metric":"IOPS_PER_MONTH","unit":"IOPS","price":[{"unitQuantity":"10","tier_model":"Granular Tier","price":1.5,"quantity_tier":"1"}],"quantity":0,"rateable_quantity":0,"cost":0}],"plan_name":"Flex (Recommended)"}],"resource_name":"Db2 on Cloud"},{"resource_id":"IBM-Performance-Hub-1.0","billable_cost":0,"non_billable_cost":0,"plans":[{"plan_id":"Free-IBM-Performance-Hub-1.0","billable":true,"pricing_plan_id":"billable:v4:Free-IBM-Performance-Hub-1.0::1483228800000:","cost":0,"usage":[{"metric":"DATA_POINTS_PER_MONTH","unit":"DATA_POINT","price":[],"quantity":34744,"rateable_quantity":34744,"cost":0}],"plan_name":"Lite"}],"resource_name":"Availability Monitoring"}],"account_id":"b87803451a162963d8bb5a1adb1b16c8","organization_id":"eu-gb:2ac382ee-42ec-435d-9c22-bc08128e3a3d","organization_name":"HydroMeteo","month":"2018-04"}

REQUEST: [2018-04-06T08:33:56+02:00]
GET /v4/accounts/b87803451a162963d8bb5a1adb1b16c8/organizations/eu-de:f335963d-0b23-4795-ba78-65b89b149601/usage/2018-04?_names=true HTTP/1.1
Host: metering-reporting.eu-gb.bluemix.net
Accept: application/json
Accept-Language: en_US
Accept-Language: en
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: IBM Cloud CLI 0.6.6 / windows



RESPONSE: [2018-04-06T08:33:57+02:00] Elapsed: 749ms
HTTP/1.1 200 OK
Content-Length: 1297
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Fri, 06 Apr 2018 06:33:58 GMT
Etag: W/"511-opxAhK9LE5dynsaSfrWWoJhxMBA"
Vary: Accept-Encoding
X-App-Index: 0
X-App-Name: metering-reporting
X-App-Version: 4.0.0
X-Heap-Used: 48672784
X-Instance-Id: 41
X-Instance-Index: 0
X-Node-Version: v6.13.0
X-Powered-By: Express
X-Process-Id: 41
X-Response-Time: 726.430
X-Uptime: 2023786.496

{"pricing_country":"EURO","currency_code":"EUR","billing_country":"NLD","resources":[{"resource_id":"cloudant","billable_cost":8.68637,"non_billable_cost":0,"plans":[{"plan_id":"cloudant-standard","billable":true,"pricing_plan_id":"billable:v4:cloudant-standard::1490943600000:","cost":8.68637,"usage":[{"metric":"LOOKUPS_PER_MONTH","unit":"LOOKUP","price":[{"unitQuantity":"100","tier_model":"Step Tier","price":18.8,"quantity_tier":"1"}],"quantity":15.4,"rateable_quantity":15.4,"cost":2.8952},{"metric":"WRITES_PER_MONTH","unit":"WRITE","price":[{"unitQuantity":"100","tier_model":"Step Tier","price":37.61,"quantity_tier":"1"}],"quantity":7.7,"rateable_quantity":7.7,"cost":2.89597},{"metric":"QUERIES_PER_MONTH","unit":"QUERY","price":[{"unitQuantity":"100","tier_model":"Step Tier","price":376,"quantity_tier":"1"}],"quantity":0.77,"rateable_quantity":0.77,"cost":2.8952},{"metric":"STORAGE_MANAGED_PER_MONTH","unit":"GIGABYTE","price":[{"unitQuantity":"100","tier_model":"Step Tier","price":75.22,"quantity_tier":"1"}],"quantity":0,"rateable_quantity":0,"cost":0}],"plan_name":"Standard"}],"resource_name":"Cloudant NoSQL DB"}],"account_id":"b87803451a162963d8bb5a1adb1b16c8","organization_id":"eu-de:f335963d-0b23-4795-ba78-65b89b149601","organization_name":"HydroMeteo","month":"2018-04"}

REQUEST: [2018-04-06T08:33:57+02:00]
GET /v4/accounts/b87803451a162963d8bb5a1adb1b16c8/organizations/us-south:89c783d4-50e7-48fa-8279-f54e45b53208/usage/2018-04?_names=true HTTP/1.1
Host: metering-reporting.eu-gb.bluemix.net
Accept: application/json
Accept-Language: en_US
Accept-Language: en
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: IBM Cloud CLI 0.6.6 / windows



RESPONSE: [2018-04-06T08:33:57+02:00] Elapsed: 349ms
HTTP/1.1 500 Internal Server Error
Content-Length: 115
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Fri, 06 Apr 2018 06:33:58 GMT
Etag: W/"73-HfpKaQjrIPFdT4rHX4O0uwnJH4U"
Vary: Accept-Encoding
X-App-Index: 0
X-App-Name: metering-reporting
X-App-Version: 4.0.0
X-Heap-Used: 41286592
X-Instance-Id: 42
X-Instance-Index: 0
X-Node-Version: v6.13.0
X-Powered-By: Express
X-Process-Id: 42
X-Response-Time: 324.902
X-Uptime: 2030832.365

{"errors":[{"code":"v4_abacus_reporting_query_error","message":"Unable to query v4 abacus reporting for reports"}]}
FAILED
Could not get usage data for org 'HydroMeteo' in region 'us-south'.Error: Error response from server. Status code: 500; description: error: {code: v4_abacus_reporting_query_error, message: Unable to query v4 abacus reporting for reports}.

**Comment by OlivierJacques** [comment]
Hi Bo, 
As soon as you have reviewed the trace, can you delete it from this trail as it may contains confidential information that I prefer to not leave it published. 
For the future (I'm new in using GitHub) how can I restrict access of delivered material?

**Comment by OlivierJacques** [comment]
Hello @archerzz , No we have several regions that are us-south, eu-gb and eu-de.

**Comment by OlivierJacques** [comment]
@archerzz yes the UI looks good with billing details of the three regions.

**Comment by OlivierJacques** [comment]
Hi Bo, thank you for asking. No the problem was solved after a new CLI version. You can close this issue.
