### ISSUE TITLE
IBM Cloud CLI version

### ISSUE THREAD

**Issue by farnaztoussi** [IBM-Cloud/ibm-cloud-cli-release#37]
The Windows 64 bit: installer on https://console.bluemix.net/docs/cli/reference/bluemix_cli/get_started.html#getting-started is an old version and the following command fails. How can I get version 0.4.9
-----------------------------------
$ bx plugin install container-service -r Bluemix
Looking up 'container-service' from repository 'Bluemix'...
Attempting to download the binary file...
21060096 bytes downloaded
Installing plugin...
FAILED
Plug-in being installed requires a minimum CLI version 0.4.9. Current CLI version is 0.3.1. Go to https://clis.ng.bluemix.net to install the latest CLI and try again.

**Comment by boyang9527** [comment]
pls go to https://clis.ng.bluemix.net to download the latest IBM Cloud CLI. 
Here is the direct link for win64: https://clis.ng.bluemix.net/download/bluemix-cli/latest/win64

**Comment by farnaztoussi** [comment]
This is the one I have downloaded and installed, but it give me the error message. Is there a later version or I have to move to Window 10?

**Comment by boyang9527** [comment]
please show me your version by running 'bx -v'
