### ISSUE TITLE
bx cr build returns 0 even if it fails to build image

### ISSUE THREAD

**Issue by htmlauthor** [IBM-Cloud/ibm-cloud-cli-release#39]
Hi,
We are using 

> bx cr build

 in DevOps pipelines to build and push docker images to private registry on IBM Cloud. We have noticed that from time to time build fails (ends somewhere in the middle, like Step 5/7 and remaining steps never run). Even if it fails bx cr build command returns 0 which means "OK" - no error. This leads to false positive on our pipeline.

I am not sure which component fails to report failure. It might be bx it'self or cr plugin.

**Comment by boyang9527** [comment]
@tim.gp@uk.ibm.com can you take a look at this issue?
