### ISSUE TITLE
Need a batch mode to delete/update multiple instances

### ISSUE THREAD

**Issue by jamesgua** [IBM-Cloud/ibm-cloud-cli-release#41]
In automation test we create instance, if any failure, may create multiple instances with same name.
I didn't find a way in CLI to delete such instances with "--force" option, and not even option with tag so no way to distinguish those instances when delete.

Without the batch mode we have to manually clean the workspace if testing failed, but it's a feature rather than an issue I'd say.

**Comment by boyang9527** [comment]
you can use ID as argument to delete the instance

**Comment by boyang9527** [comment]
Here is the usage:
```
ibmcloud resource service-instance-delete
FAILED
Incorrect Usage.

NAME:
  service-instance-delete - Delete service instance

USAGE:
   ibmcloud resource service-instance-delete (NAME|ID) [-f, --force] [--recursive]

OPTIONS:
   -f, --force  Force deletion without confirmation
   --recursive  Delete all belonging resources
```
you can run `ibmcloud resource service-instance-delete INSTANCE_ID -f  --recursive` to delete the instance if there are multiple instances that have the same name.
