### ISSUE TITLE
bx 0.7+ broken on Macosx Sierra (10.12.6)

### ISSUE THREAD

**Issue by gtasm** [IBM-Cloud/ibm-cloud-cli-release#45]
The bx command v0.7.0 and v0.7.1 cannot "bx login" (I get a dial tcp: i/o timeout every time)

The same bx command v0.6.7 can "bx login", and "bx target -o ... -s ..." also works. But when I "bx wsk action list, the command blocks on trying to get a new authentication key: 

bx wsk action list -d -i (same behavior without -i)
[main.(*WskPlugin).Run    ]:056:[Inf] Command args: [cloud-functions action list -d -i]
[main.(*WskPlugin).Run    ]:070:[Inf] Current config: &{Region:eu-de BxApiHost:https://api.eu-de.bluemix.net ... IsLoggedIn:true IAMToken:...
[main.(*WskPlugin).Run    ]:074:[Inf] Previous config: ...
[in/cli.IsOrgNameCompliant]:121:[Err] regexp.MatchString(FirmFunding) result: true
[/cli.IsSpaceNameCompliant]:133:[Err] regexp.MatchString(prod) result: true
[main.(*WskPlugin).Run    ]:132:[Inf] Using apihost openwhisk.eu-de.bluemix.net
[main.needToGetAuthKey    ]:313:[Inf] Space guid changed; need to obtain a new auth key
[main.(*WskPlugin).Run    ]:161:[Inf] Need to (re)authenticate with Cloud Functions
REQUEST:
[POST]	https://openwhisk.eu-de.bluemix.net/bluemix/v2/authenticate

[n.AuthenticateUserWithWsk]:068:[Err] HTTP Do() [req https://openwhisk.eu-de.bluemix.net/bluemix/v2/authenticate] error: Post https://openwhisk.eu-de.bluemix.net/bluemix/v2/authenticate: dial tcp: lookup openwhisk.eu-de.bluemix.net on 192.168.0.254:53: read udp 192.168.0.32:55904->192.168.0.254:53: i/o timeout
[main.getWskAuthKey       ]:385:[Err] GetNamespaces() failed: Post https://openwhisk.eu-de.bluemix.net/bluemix/v2/authenticate: dial tcp: lookup openwhisk.eu-de.bluemix.net on 192.168.0.254:53: read udp 192.168.0.32:55904->192.168.0.254:53: i/o timeout
[main.(*WskPlugin).Run    ]:164:[Err] getWskAuthKey() failed: Unable to obtain wsk authentication key: Post https://openwhisk.eu-de.bluemix.net/bluemix/v2/authenticate: dial tcp: lookup openwhisk.eu-de.bluemix.net on 192.168.0.254:53: read udp 192.168.0.32:55904->192.168.0.254:53: i/o timeout
Unable to authenticate with Cloud Functions: Unable to obtain wsk authentication key: Post https://openwhisk.eu-de.bluemix.net/bluemix/v2/authenticate: dial tcp: lookup openwhisk.eu-de.bluemix.net on 192.168.0.254:53: read udp 192.168.0.32:55904->192.168.0.254:53: i/o timeout

Is there a way to fix bx 0.7+ or to make 0.6.7 wsk plugin work? 

Thanks in advance!

**Comment by archerzz** [comment]
@gtasm This seems not a problem in CLI or plugin. There are some problems in the network configuration of the endpoint `https://api.eu-de.bluemix.net/`. As you posted, the plugin cannot connect to openwhisk server either.

I used `dig` to probe the endpoint, and the same error happened. I suggest you should file a ticket to openwhisk, letting them check the availability of `https://api.eu-de.bluemix.net/`

```
➜  ~ dig https://openwhisk.eu-de.bluemix.net/bluemix/v2/authenticate

; <<>> DiG 9.10.6 <<>> https://openwhisk.eu-de.bluemix.net/bluemix/v2/authenticate
;; global options: +cmd
;; connection timed out; no servers could be reached
```

**Comment by archerzz** [comment]
@gtasm When you execute `bx login`, what's the endpoint you target?

**Comment by weieigao** [comment]
@gtasm  as archerzz said, it could be a network problem. I can successfully log into api.eu-de.bluemix.net on my side. What's the url when you got the dial time out error?

**Comment by gtasm** [comment]
Thanks weieigao and archerzz for your answers!

I have executed the same HTTP requests using a REST client and the response came straight away (containing my auth token and refresh token, then the second response containing the uuids and keys of my openwhisk namespaces). The only tool that blocked on the authentication was my bx wsk command line tool.

To login, I used the following command: 
bx login -a https://api.eu-de.bluemix.net -o ... -s ...
It worked as usual (with 0.6.7) and I could run any bx (info, account, etc) command afterwards. 
The same bx login -a https://api.eu-de.bluemix.net -o ... -s ... using 0.7.0 and 0.7.1 blocked till their timeout raised.

Once logged in using bx v.0.6.7, the command raising the dial time out was "bx wsk action list". Displaying the detailed info (-d), I can see the URL that is blocking: 
[POST]	https://openwhisk.eu-de.bluemix.net/bluemix/v2/authenticate

The debug also displays the JSON payload of the HTTP POST request. I can easily copy it and replay it using my REST client. And it works perfectly, giving me the (pardon me, I just replace prive data with ...):
{
  "subject": "...",
  "developer_guid": "...",
  "namespaces": [
    {
      "name": "..._dev",
      "key": "...",
      "uuid": "..."
    },
    {
      "name": "..._prod",
      "key": "...",
      "uuid": "..."
    }
  ],
  "additionalKeys": {
    "bluemix": {
      "accessToken": "...",
      "refreshToken": "..."
    }
  }
}

Feel free to have me testing anything else to solve this problem.

**Comment by archerzz** [comment]
@gtasm Are you using VPN on macOS? There is regression in `0.7.0` and `0.7.1`, and we will fix it in the coming `0.8.0`.

**Comment by gtasm** [comment]
No, I use a raw / direct connection.

Le lun. 2 juil. 2018 à 04:29, Mingzhe Huang <notifications@github.com> a
écrit :

**Comment by mishindm** [comment]
It looks like I have same problem and it's the problem with 0.7.1 only. 
The different urls - perfectly well accessible using curl are causing errors with bx, e.g.
Get https://mccp.ng.bluemix.net/v2/regions: net/http: TLS handshake timeout

The same issue is with other requests, e.g. registry, https://clis.ng.bluemix.net/info

The 0.6.7 running in the container based on the same physical host is working. Is there some way to downgrade CLI to 0.6.7?

**Comment by boyang9527** [comment]
@gtasm @mishindm  does v0.8.0 solve your issue?
https://console.bluemix.net/docs/cli/reference/ibmcloud/all_versions.html#all-versions-of-the-ibm-cloud-cli-installer

**Comment by mishindm** [comment]
Upgraded bx and plugins are working for now.

**Comment by leucir** [comment]
Any workaround for this?

```
bx update
Checking for updates...
FAILED
An error occurred when retrieving CLI info:
Get https://clis.ng.bluemix.net/info: net/http: TLS handshake timeout
Try again later.
```

```
bx login --sso
FAILED
Could not retrieve api endpoints for public regions.
Get https://mccp.ng.bluemix.net/v2/regions: net/http: TLS handshake timeout
```

**Comment by boyang9527** [comment]
@mishindm  which 'bx cs' command you were running?  pls bring up your kubernetes sevice plugin to latest.  `ibmcloud plugin install container-service`

**Comment by mishindm** [comment]
bx plugin update --all
Checking upgrades for all installed plug-ins from repository 'Bluemix'...
No updates are available.

bx cs region-set eu-central
bx cs cluster-config  <cluster>

Right now these commands are working. The same was this morning.

At the moment when I was updating the previous comment they both were failing from macOS and working from linux docker.

**Comment by gtasm** [comment]
At last! 

I finally wiresharked my problem and found the issue: my "bx wsk" (and "bx cf") client uses a buggy DNS resolver. This probably comes with go-lang. 

I didn't fix it but found a simple workaround that does the job for me: suffices to edit the local "/private/etc/hosts" file and to add the following line:
158.177.81.248 openwhisk.eu-de.bluemix.net

I just wanted to share this "half solution" for those among you who may cope with the same issue.

Thanks everybody for your feedback!
