### ISSUE TITLE
IBM Cloud CLI SoftLayer File Storage Ordering Does Not Support Hourly Billing

### ISSUE THREAD

**Issue by rickysway** [IBM-Cloud/ibm-cloud-cli-release#48]
Currently the IBM Cloud command line tool for infrastructure services does not support hourly billing for ordering file storage. By default, file storage volumes ordered through command line are charged monthly. (Hourly billing is available through slcli and SL UI)

Eg. [bx sl file volume-order -t endurance -s 20 -e 0.25 -d ams03 --billing hourly]
Returns:

FAILED
flag provided but not defined: -billing

**Comment by YouHang** [comment]
Hi,
Thanks, We are working on it. I will update this issue when this feature is completed.

**Comment by YouHang** [comment]
Hi, this issue have already been fixed. Thanks
