### ISSUE TITLE
ibmcloud cli autocompletion is not working on Mac OS

### ISSUE THREAD

**Issue by fg78nc** [IBM-Cloud/ibm-cloud-cli-release#49]
First of all documented path does not exist
source /usr/local/ibmcloud/autocomplete/zsh_autocomplete into ~/.zshrc.

I found autocompletion script under ../ibmcloud/bx folder, but seems like they are not functional for ibmcloud cli (not bluemix)
Any clues?

**Comment by boyang9527** [comment]
The doc is not synchronized. The auto-completion script path will be changed to /usr/local/ibmcloud/autocomplete from v0.9.0(coming in  a couple of days)

@weieigao, pls look at this issue.

**Comment by weieigao** [comment]
@boyang9527 ok

**Comment by weieigao** [comment]
@fg78nc if your cli version is `0.8.0`, run the following command:
```
source /usr/local/ibmcloud/bx/zsh_autocomplete
```
And see if auto completion works.
