### ISSUE TITLE
Failed to list VLANs on your account. json: cannot unmarshal number into Go struct field Error.code of type string

### ISSUE THREAD

**Issue by ezmoneySniper** [IBM-Cloud/ibm-cloud-cli-release#50]
when I run the ibmcloud sl vlan list command I get the following message

Failed to list VLANs on your account.
json: cannot unmarshal number into Go struct field Error.code of type string

Is this my account error or the cli error

**Comment by boyang9527** [comment]
which version you are using?  type 'ibmcloud -v'

**Comment by ezmoneySniper** [comment]
ibmcloud version 0.8.0+50d0d38c-2018-07-11T06:52:10+00:00

this is the version that i have currently

**Comment by boyang9527** [comment]
@youhwsh@cn.ibm.com  pls look at this issue.

**Comment by YouHang** [comment]
Hi @ezmoneySniper , this should already be fixed by SL API. I didn't reproduce this issue on my end. can you try again? 
if you still have this issue, please post the trace log here by using: `ibmcloud config --trace=true` 

https://github.com/IBM-Cloud/ibm-cloud-developer-tools/issues/53

**Comment by YouHang** [comment]
Hi @ezmoneySniper , Thanks. I found the api endpoint you use was not right.
Normally, SL Cli will use `https://api.softlayer.com/mobile/v3.1` as a endpoint to assess sl resource.
but in your log, sl cli use `api.ng.bluemix.net`, that was not correct.
Did you use ENV_SL_API_ENDPOINT="api.ng.bluemix.net" to set ENV_SL_API_ENDPOINT?
if yes, you can use `export ENV_SL_API_ENDPOINT="https://api.softlayer.com/mobile/v3.1"` or `export ENV_SL_API_ENDPOINT=""` to change the api endpoint right.

finally, the sl init output will like this:
```
Choose how to configure Softlayer authentication:
1. Login with Softlayer user name and password/API key
2. Use IBM Cloud Single-Sign-On
Enter a number> 2
API endpoint URL: [https://api.softlayer.com/mobile/v3.1]>
```

but this was indeed an issue with sl API, we will work on it to make it more robust.

**Comment by ezmoneySniper** [comment]
Thank you @YouHang that solved my problem!
