### ISSUE TITLE
ibmcloud wsk doesn't show help

### ISSUE THREAD

**Issue by sudoalger** [IBM-Cloud/ibm-cloud-cli-release#51]
When using `ibmcloud wsk --help` it shows:

```
NAME:
  cloud-functions, wsk, functions, fn - IBM Cloud CLI plug-in for IBM Cloud Functions

USAGE:
   Issue 'ibmcloud cloud-functions' for detailed help
```

As a user, I expect it would automatically go to `help`. However, using `ibmcloud wsk` it goes to:

```
IBM Cloud CLI plug-in for IBM Cloud Functions
Usage:
  wsk [command]

Available Commands:
  action      work with actions
  activation  work with activations
  package     work with packages
  rule        work with rules
  trigger     work with triggers
  sdk         work with the sdk
  property    work with whisk properties
  namespace   work with namespaces
  list        list entities in the current namespace
  api         work with APIs
  service     Bind and unbind service credentials to an action or package.


Flags:
      --apihost HOST         whisk API HOST
      --apiversion VERSION   whisk API VERSION
  -u, --auth KEY             authorization KEY
      --cert string          client cert
  -d, --debug                debug level output
  -h, --help                 help for wsk
  -i, --insecure             bypass certificate checking
      --key string           client key
  -v, --verbose              verbose output

Use "wsk [command] --help" for more information about a command.
```

You should be able to use `ibmcloud wsk --help` and get the above information as well. Adding `--help` and not getting anything vs not adding `--help` and getting a list of `wsk` options seems counterproductive.

**Comment by boyang9527** [comment]
@mdeuser@us.ibm.com, pls take a look at this issue.

**Comment by mdeuser** [comment]
@boyang9527 - there is already an issue opened for this; however, it's a low priority item whose fix is somewhat tricky due to the nature of how the cloud-functions plugin wrappers the openwhisk cli.

**Comment by boyang9527** [comment]
Got u, thanks. Then  I will leave this issue open.  Please update this issue once you get a chance to get it fixed.

**Comment by archerzz** [comment]
@mdeuser Is this issue fixed?

**Comment by mdeuser** [comment]
hi @archerzz - no this has not been fixed.  our plugin ownership is being transferred once again which is causing many of our plugin defects to grow stale.  https://github.ibm.com/BlueMix-Fabric/bluemix-openwhisk-cli/issues/56
