### ISSUE TITLE
feature request: provide a command to list available endpoints

### ISSUE THREAD

**Issue by snowch** [IBM-Cloud/ibm-cloud-cli-release#54]
When moving between regions, I have to do a google search to find the appropriate endpoint.  Could we introduce a command (e.g. 'targets') that listed the available endpoints?

**Comment by boyang9527** [comment]
when you login without previous endpoint set you will be prompted by available endpoints.  Run `ibmcloud api --unset` to clear the previous endpoint setting. 

If you want to switch region after login, run `ibmcloud target -r REGION_NAME`,  you can use `ibmcloud regions` to get all the regions.

**Comment by boyang9527** [comment]
please reopen if the answer does not solve your issue
