### ISSUE TITLE
CAN NOT run cli on raspbian or armbian? how to run  cli on raspbian or armbian?

### ISSUE THREAD

**Issue by bluegod1996** [IBM-Cloud/ibm-cloud-cli-release#55]
CAN NOT run cli on raspbian or armbian? how to run  cli on raspbian or armbian?

**Comment by boyang9527** [comment]
right now we don't have plan to support these two platforms

**Comment by ScottMorse** [comment]
I just want to add my support for having it come to these platforms, as groups and individuals using Raspberry Pis as IoT devices, for even just sandboxing, are looking for solutions for managing them through cloud platforms.

**Comment by archerzz** [comment]
@ScottMorse @bluegod1996 It's quite straightforward to add linux arm64 into support. But you might need kubectl/docker cli/cf cli as well. They don't provide linxu arm64 support.

**Comment by steveclay** [comment]
There is now Linux ARM provided as an as-is release.
