### ISSUE TITLE
IBM Cloud Infrastructure CLI  - Feature request

### ISSUE THREAD

**Issue by Sebaschaparro** [IBM-Cloud/ibm-cloud-cli-release#56]
Dear all,

When deploy monthly Baremetals, there's not option to select VMware VSphere as OS. Is it possible to include VMware to the Available OS list?

Regards.

**Comment by YouHang** [comment]
Thanks @Sebaschaparro ! Working on this feature

**Comment by Sebaschaparro** [comment]
Hi,

Many thanks! Really appreciated

Sebas.
