### ISSUE TITLE
ibmcloud cf help does not list delete-domain

### ISSUE THREAD

**Issue by nitind** [IBM-Cloud/ibm-cloud-cli-release#62]
0.10.1+793a333-2018-09-20T06:29:40+00:00

The help output doesn't include the delete-domain command, even though it does work:

> ```
> Route and domain management:
>   routes,r        delete-route    create-domain
>   domains         map-route
>   create-route    unmap-route
> ```

**Comment by boyang9527** [comment]
use `ibmcloud cf help -a`
