### ISSUE TITLE
Install plugins into custom/system directory

### ISSUE THREAD

**Issue by msogrin** [IBM-Cloud/ibm-cloud-cli-release#64]
By default, the plugins are installed into the current user's home directory.
I'm looking for the ability to install plugins system-wide, same as the IBM Cloud CLI itself, preferably into the same directory.

Usecase: installing IBM Cloud CLI *with plugins* in a Jenkins slave Docker image, so that Jenkins jobs could execute `ibmcloud` commands with plugins.
- even if the plugins were installed into `/home/jenkins/.bluemix` during Docker image build, this directory and everything in `/home/jenkins` is removed with Jenkins' own files during runtime.
- workaround is to install plugins during runtime of every Jenkins job from inside the Jenkins job. While very inefficient, this approach works most of the time, but fails if `IBM Cloud` plugin repository is not available for some reason, which usually happens several times a day.

**Comment by msogrin** [comment]
Any chance to implement this?

**Comment by ylecleach** [comment]
I am from BNP Paribas group (CARDIF insurance), our target is Windows 10. We have also this urgent need as we can not choose either : 
- the root directory for binaries installation (always in C:/Program Files).
- the config and plugins (and its binaries) directory.
For this last, the home directory is a logical disk on the network and limited to 1 Gb. (windows remote profile).

In addition, all the IDT (IBM Developer tools) should be installable in User Mode (non Admin), and support a Proxy Mode.
Ideally all IBM Cloud CLI  should also been compatible with Cygwin64, which is heavily used by Java developer who are limited to  use a Windows 10 OS.

Thank you for you possible feedback.

**Comment by razvan-balan** [comment]
We need to install ibmcloud plugins on machines with multiple user accounts.
We're using Ansible and we put in a command like this into an Ansible playbook: 
_ibmcloud plugin install -f -r Bluemix container-service_

Due to the above limitation, the plugin gets installed only for the Ansible user. 
The other users are missing the plugin which is very inconvenient.

**Comment by thomasmhofmann** [comment]
I would also be very interessted in this feature. This way it would be possible to provide a set of files that can just be used without any installation steps needed.
We are keeping a bunch of needed static binaries in our SCM and cannot do this for the CLI plugins.

**Comment by steveclay** [comment]
You can change the location of the IBM Cloud CLI's configuration by using the `IBMCLOUD_HOME` variable. See this article for more details:  https://cloud.ibm.com/docs/cli?topic=cli-ibmcloud-home
