### ISSUE TITLE
Use StdErr for messages

### ISSUE THREAD

**Issue by sdaschner** [IBM-Cloud/ibm-cloud-cli-release#67]
It would greatly improve the ability to pipe & combine the ibmcloud CLI with other commands, if the messages are routes to stderr.

Example:
```
$> ibmcloud --version
ibmcloud version 0.12.1+a6d7092-2018-11-19T02:43:43+00:00

$> ibmcloud cs clusters > /tmp/file
$> cat /tmp/file
OK
Name            ID ...
...
<cluster upgrade message>
```
It's very helpful to suppress the messages with `-s`, however, having this distinction enabled, would allow to both see the messages and not use them for chained commands.

Please also see: https://medium.com/@jdxcode/12-factor-cli-apps-dd3c227a0e46

**Comment by archerzz** [comment]
@weieigao I remember we've discussed about the output format, and we've touch this area.

**Comment by sdaschner** [comment]
Any updates on this?

**Comment by sdaschner** [comment]
:+1: for different verbosity levels.

But just to double-check we're on the same page: Even for the quiet mode (and for all others) error and info messages *should* go to StdErr.

E.g. if there's only an error to be displayed and no proper output then there'd be no output to StdOut, only to StdErr

**Comment by sdaschner** [comment]
Any updates on this? Happy to help in any way.

**Comment by alex-slynko** [comment]
Hi,
Are there any updates for this?
It breaks my automation and I don't see the messages.

**Comment by sdaschner** [comment]
@weieigao @jsloyer Ping :)
