### ISSUE TITLE
command bx login --no-iam does not work in bx version 0.13.0

### ISSUE THREAD

**Issue by daniimara** [IBM-Cloud/ibm-cloud-cli-release#69]
**➜  ~ bluemix api https://api.w3ibm.bluemix.net**
Setting api endpoint to https://api.w3ibm.bluemix.net...
OK

API endpoint: https://api.w3ibm.bluemix.net
Not logged in. Use 'bluemix login' to log in.
**➜  ~ bx login --no-iam**
API endpoint: https://api.w3ibm.bluemix.net

Email> ibmid@br.ibm.com

Password> 
Authenticating...
OK

Targeted account CIO Cloud Services Public Dedicated (e97a8c01ac694e308ef3ad7795e20d7e)

                      
API endpoint:      https://api.w3ibm.bluemix.net   
Region:            w3ibm:prod:us-south   
User:              ibmid@br.ibm.com   
Account:           CIO Cloud Services Public Dedicated (e97a8c01ac694e308ef3ad7795e20d7e)   
Resource group:    No resource group targeted, use 'bx target -g RESOURCE_GROUP'   
CF API endpoint:   https://api.w3ibm.bluemix.net (API version: 2.75.0)   
Org:                  
Space:                

Tip: If you are managing Cloud Foundry applications and services
- Use 'bx target --cf' to target Cloud Foundry org/space interactively, or use 'bx target --cf-api ENDPOINT -o ORG -s SPACE' to target the org/space.
- Use 'bx cf' if you want to run the Cloud Foundry CLI with current IBM Cloud CLI context.

**➜  ~ bx target --cf**
Targeted Cloud Foundry (https://api.w3ibm.bluemix.net)

                   
API endpoint:   https://api.w3ibm.bluemix.net   
Region:         w3ibm:prod:us-south   
**_Not logged in. Use 'bx login' to log in._**
➜  ~

**Comment by boyang9527** [comment]
Moved to IBM repo.
