### ISSUE TITLE
Better integration with kubectl cluster contexts

### ISSUE THREAD

**Issue by sdaschner** [IBM-Cloud/ibm-cloud-cli-release#70]
It would highly improve the developer experience if there'd be a simple way to add IKS clusters to the *default* kubectl context (usually under `~/.kube`). Instead of setting the `KUBECONFIG` environment variable every time (and in every shell), getting the credentials of a created IKS cluster and integrating them into the `~/.kube/config` YAML would facilitate the steps for users.

To create and connect to a new IKS cluster, the desired steps could look as follows:
- Create cluster via Browser or `ibmcloud cs cluster-create`
- `ibmcloud cs cluster-get-credentials <cluster>` (or similar)
- `kubectl config use-context iks-...-<cluster>` (optional, could already be switched by previous cmd)
- `kubectl cluster-info` (newly created cluster)

I currently use a home-grown shell script to achieve the same: https://github.com/sdaschner/ibm-cloud-tools/blob/master/ibmcloud-add-cluster

You can also have a look a the gcloud CLI of GCP: `gcloud container get-credentials ...` which adds the cluster to the `kubectl` config.

By doing so, users don't have to (manually) set environment variables or similar things. Executing simple CLI commands should be sufficient.

**Comment by sdaschner** [comment]
@svennam92 @jjasghar Any thoughts on this?

**Comment by svennam92** [comment]
Great idea. Have seen this issue quite often during workshops when attendees accidentally open a new terminal and lose the KUBECONFIG env var.

**Comment by sdaschner** [comment]
Whom to ping regarding updates on this?
For myself, I've created a (quick&dirty) [shell script](https://github.com/sdaschner/ibm-cloud-tools/blob/master/ibmcloud-add-cluster) for now.

**Comment by JohnStarich** [comment]
Hey there, I’m a maintainer on the IKS CLI plugin! This is great idea. I'm a little fuzzy on the details for how this would work, but a custom version of `~/.kube/config` appended to `KUBECONFIG` does seem like way better UX.

Unfortunately, we can't auto-export things from the CLI without an entirely new "wrapper" on it. This is because the `ibmcloud ks` and `ibmcloud` commands both run as executables. The only way to auto-export a variable is be part of the current shell's runtime -- which is much more difficult to do than it sounds. If you want to script it, you can do this today:
```bash
eval $(ibmcloud ks cluster-config --export ...)
```

One way we could do this is by asking the user to add something to `KUBECONFIG`, but make it a static file path. Something like
```bash
export KUBECONFIG=$KUBECONFIG:~/.bluemix/plugins/container-service/config
```
that users can add to their shell's profile (e.g. `~/.bash_profile`, `~/.zshrc`).
Then our plugin could manage this path to point to all of your IKS clusters, without impacting any local setup the user already has. I'm not sure we want to modify the global `~/.kube/config` one, but it's worth investigating if it's manageable. What are your thoughts on using a default vs. custom config?

**Comment by nibalizer** [comment]
This is the script I use: https://github.com/nibalizer/very_misc_scripts/blob/master/bxk8s

And here are the hacks that Dan Berg (DE on IKS) recommends on medium: https://medium.com/@dancberg/how-to-setup-an-awesome-shell-experience-for-ibm-cloud-kubernetes-service-285467ddd455

**Comment by sdaschner** [comment]
TBH asking the developer to do anything with their kubeconfig is not an improvement to the developer experience. I'd expect `ibmcloud` to add the cluster to my (global) contexts (so that it simply works to switch) without requiring to change the environment temporarily nor permanently (i.e. `KUBECONFIG`) nor breaking what's currently available.

Changing the (single) global config seems the cleanest and least hacky part to me. Therefore we minimize the number of moving parts. This is also how GKE does it and to me as a user that was always very convenient (simply is there, or switchable via `kubectl config use-context`).

**Comment by jjasghar** [comment]
I've actually added something in my **BETA** Kube201: https://ibm.gitlab.io/workshop/kube201/#pimp

**Comment by JohnStarich** [comment]
Thank you all for your input! We just added **experimental** support for this to the Kubernetes Service plugin (version 0.3.112). We decided to merge the downloaded credentials into the existing kubeconfig file, based on your suggestions.

**This is still experimental**, so things may change between now and it's intended release, but I know you probably want to try it out early 😄 

To use the new behavior, update to the latest plugin (version 0.3.112) and then enable experimental behavior:
```bash
ibmcloud plugin update kubernetes-service
export IKS_BETA_VERSION=1.0
```
Now you can run `ibmcloud ks cluster config --cluster mycluster` to automatically set up your config 🎉 

Note: If you have set the `KUBECONFIG` environment variable already, the new config will be merged into the first file in that var. That way you can run `kubectl` commands _immediately_ after running `ibmcloud ks cluster config`, no matter how your files are set up.

**Comment by sdaschner** [comment]
Awesome! Thanks a lot John!

**Comment by josephdibartolo** [comment]
Do we have a timeline on when this will be non-experimental? It seems like you still need to `export IKS_BETA_VERSION=1.0` in order for this to work.

**Comment by sdaschner** [comment]
@JohnStarich FYI, that URL gives me a 400 error...

**Comment by JohnStarich** [comment]
Thanks for letting me know. Seems like intermittent issues with the blog today. I’ve reached out to the blog team and they’re taking a look.

**Comment by JohnStarich** [comment]
Hi all, thanks for hanging in there for this feature. Just a quick update: version 1.0 of the IKS plugin is going out March 16th!

The blog post above has been updated with the date as well ^

**Comment by JohnStarich** [comment]
**Version 1.0.0 of the `ks`/`oc` CLI plugin was released today!** 🚀 
To update your CLI plugin, run `ibmcloud plugin update kubernetes-service`

**Comment by starpit** [comment]
Did I get this right? If i have a KUBECONFIG env var with many clusters in a colon-separated list, then running `ibmcloud ks cluster config --cluster foo` will result in completely overwriting whatever config file happens to be at the end of the list? even if that entry has nothing to do with the cluster being configured?

Can someone help me to understand why this is a good idea? Your plugin just trashed one of my kubernetes configs for a cluster unrelated to the ibmcloud container/kubernetes service.
