### ISSUE TITLE
Specifying API endpoint during login causes "runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by lgfa29** [IBM-Cloud/ibm-cloud-cli-release#71]
I am setting up an automated process that will use the `ibmcloud` CLI, but if I try to run `ibmcloud login` specifying an endpoint with `-a` parameter along with other settings I get this error:

```
runtime error: invalid memory address or nil pointer dereference
```

The command I am using to login is this:

```sh
ibmcloud login \
  -a "$IBMCLOUD_API_ENDPOINT" \
  -r "$IBMCLOUD_REGION" \
  -c "$IBMCLOUD_ACCOUT_ID" \
  -g "$IBMCLOUD_RESOURCE_GROUP"
```

If I break this into two commands where the endpoint is specified by itself I don't get this error.

**Comment by boyang9527** [comment]
it should have been fixed in v0.14.0
