### ISSUE TITLE
IBM_Cloud_CLI_0.14.0_windows_amd64.zip does not include all files

### ISSUE THREAD

**Issue by se35710** [IBM-Cloud/ibm-cloud-cli-release#73]
...only `ibmcloud_analytics.exe` and `cfcli\cf.exe` are in the achive.

**Comment by boyang9527** [comment]
sorry for that, will fix it soon

**Comment by se35710** [comment]
@boyang9527 checksum at https://clis.ng.bluemix.net/download/bluemix-cli/0.14.0/win64/archive/checksum is still wrong, returns `dc6a016d8d9030e92c2c13e851e25eed2c22da20`, but should be `0edcee50cca77c6eea247633f40a9281ef1f9531`.

**Comment by boyang9527** [comment]
thanks for reporting this. It should be fixed.
