### ISSUE TITLE
ibmcloud cs cluster create requires VLANs

### ISSUE THREAD

**Issue by sdaschner** [IBM-Cloud/ibm-cloud-cli-release#75]
In order to create a cluster via CLI, one has to provide the public and private VLANs. It would improve the user experience to make that not mandatory, similarly to the creation via browser console. If the VLANs are not provided, they could simply be created.

```
ibmcloud cs cluster create --zone fra02 --workers 4 --name some-cluster-name --machine-type b2c.4x16

Creating cluster...
FAILED
Error response from server. Status code: 400; message: {"incidentID":"...","code":"E0020","description":"To create a standard cluster, you must specify values for location, machine type, public VLAN, and private VLAN. To create a free cluster, specify cluster name only.","type":"Provisioning"}
```

**Comment by boyang9527** [comment]
@jsloyer  please take care of this feature request.

**Comment by jsloyer** [comment]
The cli does that as well.  However if you have vlans in the proposed datacenter it requires you to select them.  The ui autopopulates a pair that works...  We could take a look at this and do some logic here and if you have an appropriate pair for a datacenter we could preselect them for you.

**Comment by sdaschner** [comment]
@jsloyer Makes sense. Yes, that would help a lot!

Will do. Is that the usual process of submitting issues to the `ibmcloud` / IKS subsystem? I have a few other issues submitted in this repo already.

**Comment by jsloyer** [comment]
Yep! It would get things addressed a lot quicker!!!

**Comment by sdaschner** [comment]
Addressed in internal repo.
