### ISSUE TITLE
ibmcloud returning 0 code from a previous failed command

### ISSUE THREAD

**Issue by jmgalvez** [IBM-Cloud/ibm-cloud-cli-release#83]
We are hitting a limitation on IBM Cloud related to Access Groups. It seems to be that an user cannot be member of more than 50 AGs.

Here you have the related error (It is NOT the output of ibmcloud command line):

``  "errors": [ 
    { 
      "iam_id": "xxxxx", 
      "type": "user", 
      "created_at": "", 
      "created_by_id": "", 
      "trace": "099cae41-575a-415c-85b0-03493129eaaf", 
      "errors": [ 
        { 
          "code": "error_occurred", 
          "message": "Group membership limit reached. A member can be a member of at most 50 groups" 
        } 
      ], 
      "status_code": 403 
    }  ``

**"Group membership limit reached. A member can be a member of at most 50 groups"**

The thing is that we are using massively _ibmcloud_ command line as part of our automation setup. We are using ibmcloud version 0.15.1, which is the latest version till now.

In our opinion, _ibmcloud_ is not behaving correctly. When we add an user to an existing Access group and this user has reached the limitation of at most 50 groups...

``ibmcloud iam access-group-user-add team_ag user@mail.com``

The command output is as follows:

``Adding user@mail.com to access group team_ag as account_owner@mail.com...``
``Failed to add access group users``

or

``FAILED``
``Partial success. The following users are not added.``

The error message is OK. 

However, if you check the return code from the last run process we would expect to have a different value than 0, which means no error hapenned. Something like 1 or 2 or whatever..

``$> echo $?``
``0``

Therefore our automation tool (bash) thinks that everything went well.

**Comment by archerzz** [comment]
@jmgalvez `0.17.0` is out. Would you mind if you could have a try? Thanks.

**Comment by jmgalvez** [comment]
@archerzz Sure, I will let you know the outcomes.

**Comment by jmgalvez** [comment]
@archerzz It works fine, now we have an error code. Thank you very much!.

**Comment by archerzz** [comment]
@jmgalvez great! Then I'll close this issue. Thanks for your feedback.
