### ISSUE TITLE
broken linux installer links

### ISSUE THREAD

**Issue by slipperypenguin** [IBM-Cloud/ibm-cloud-cli-release#84]
All of the links to the Linux64 installer have a typo that results in a `404` response.

The link points to: https://clis.ng.bluemix.net/download/bluemix-acli/0.16.1/linux64
The correct links should be: https://clis.ng.bluemix.net/download/bluemix-cli/0.16.1/linux64

![Screen Shot 2019-06-05 at 4 41 39 PM](https://user-images.githubusercontent.com/3655354/58988996-f4a5a100-87b0-11e9-8be3-91075af16d98.png)

**Comment by archerzz** [comment]
@slipperypenguin this issue should have been fixed. would you mind if you could have a try? thanks.

**Comment by archerzz** [comment]
Close this issue, since it should have been fixed...
