### ISSUE TITLE
0.16.1 breaks ability to change resource groups

### ISSUE THREAD

**Issue by booninite** [IBM-Cloud/ibm-cloud-cli-release#85]
```
λ ibmcloud target -g dev-infra
FAILED
Could not get resource group:
Error response from server. Status code: 403; description: {"trace":"42467433158","errors":[{"code":"CAN_NOT_PERFORM_ACTION","message":"No permission","more_info":"n/a"}]}.
```

going back to 0.16.0 fixed my issue.

**Comment by boyang9527** [comment]
@booninite  we are aware of this issue.  This is not a CLI defect but the new resource group feature we added in 0.16.1 hits a hidden defect on backend. 

You can also use `ibmcloud target -g GROUP_ID`  to work around.  `ibmcloud resource groups` will given you the ID. 

We will have a hot fix for this today in a couple days.

**Comment by boyang9527** [comment]
@booninite  0.16.2 has the fix.

**Comment by archerzz** [comment]
@booninite Would you mind if you could upgrade to latest version and have a try? This issue should have been fixed. Thanks.
