### ISSUE TITLE
0.16.2 is unable to add some users to an access group

### ISSUE THREAD

**Issue by jmgalvez** [IBM-Cloud/ibm-cloud-cli-release#87]
Hi,

Adding users to an access group failes with 0.16.2

ibmcloud iam access-group-user-add ag user_list

if one of the user in the user_list has account management privileges..

The error is:
_FAILED
User xxx@xxx.com is not found under current account XXXXX_

which is not right, user is there and it can be checked with _ibmcloud account users._

If we roll back to 0.16.0 same command works.

**Comment by jmgalvez** [comment]
Hi,

After enabling the debug on ibmcloud, the issue seems to be related with lowercase/uppercase. 

The response from the backend is showing up the user with a capital letter at the beginning of the firstname and lastname. 

(Names have been changed)

{"id":"86e5f8bb4c59438c80a1c28541a39f41","iam_id":"IBMid-5500018PVB","realm":"IBMid","user_id":"**P**aco.**P**epe@empresa.com","firstname":"Paco","lastname":"Pepe","state":"ACTIVE","email":"**P**aco._P_epe@empresa.com","phonenumber":"","altphonenumber":"","photo":"","account_id":"a9048xxxxxxxxxxxxxxxxxx","linkages":[{"origin":"UAA","id":"3a746e6d-78a3-4c92-8ce0-3fbb81e23e3f"},{"origin":"IMS","id":"7415617"}]},

ibmcloud iam access-group-user-add ag **paco.pepe@empresa.com** (everything in lowercase).

Not sure if this can be the reason of this issue. 

Could you please check this?

Thanks.

**Comment by archerzz** [comment]
@jmgalvez I confirmed that this is a regression in `0.16.1`. We've switched the backend API and that causes regression.
But I think the original user email should be `Paco.Pepe@empresa.com`. I double checked with backend team and they confirmed the they will return the original inputs from customers. Please note that the using capital cases in user name is allowed in RFC, but not recommended in reality.

**Comment by archerzz** [comment]
Meanwhile, please roll back to `0.16.0` or input the exact case of letters of user names...

**Comment by jmgalvez** [comment]
@archerzz Thanks for the quick response. Yes, if you think on terms of RFC, RFC5321 recommend to avoid such cases in which email is case sensitive, RFC5321 obsoletes RFC 2821.

Maybe because emails systems as gmail are case insensitive, many users have adopted this thing. Our customers provide us their ibmid (email) in lowercase but some of them created the ibm cloud account using a mix of lower and upper case. 

So, having a fix on ibmcloud would be very very useful and nice for us. Thank you so much.

**Comment by archerzz** [comment]
@jmgalvez This issue should have been fixed in `0.16.3`. Would you mind if you could have a try? Thanks.

**Comment by jmgalvez** [comment]
@archerzz I have tested 0.16.2 and 0.16.3.  Yes, in 0.16.3 the issue is solved. I have been able to add the same users to same AG using only an IBMid in lowercases.

Thanks again for implementing the solution, we really appreciate it.
