### ISSUE TITLE
0.16.2 is showing VPN user name (Softlayer) instead of ibmid email name

### ISSUE THREAD

**Issue by jmgalvez** [IBM-Cloud/ibm-cloud-cli-release#88]
Hi,

When we run _ibmcloud account users_ command instead of seen the user name we are seeing the vpn user name (coming from softlayer) which add a prefix to the user name with a number... This is really weird. It is only happening on PENDING users.

Not happening with 0.16.0.

**Comment by YouHang** [comment]
Hi @jmgalvez 
Can you help to use `bx config --trace true` to open the trace log and post here?
I can't reproduce this issue on my side

**Comment by jmgalvez** [comment]
> Hi @jmgalvez
> Can you help to use `bx config --trace true` to open the trace log and post here?
> I can't reproduce this issue on my side

I tried again, manually, but this time the response from IBM seems to be valid, no more VPN numberid preffix. Unable to reproduce it.

Usually we run a jenkins job to check users accounts. I have the output from our jenkins job but I cannot share this information here due to security reasons.

**Comment by YouHang** [comment]
ok. it seems that the backend service is not stable. CLI just print the info to user.
if you encounter this issue next time, please post the trace log.
