### ISSUE TITLE
Kubernetes cmd "kubectl" is throwing bash: kubectl : command not found error

### ISSUE THREAD

**Issue by LalithVignesh** [IBM-Cloud/ibm-cloud-cli-release#9]
While using the kubectl cmd, after downloading a kubectl.exe file and placing it in the path. The error appears in command line.

This happened in Bluemix CLI.

**Comment by boyang9527** [comment]
Please provide the version  of bluemix cli and container service plugin
  - run 'bx -v' to get cli version
  - run 'bx plugin list' to get version of plugins 

I am assuming you are running windows, right? then are you using  bash for windows?

**Comment by LalithVignesh** [comment]
1. for "bx-v" i got the following response

C:\Program Files\IBM\Bluemix\bin\bx.exe version 0.6 1+724c406-2017-10-07T00:11:03+00:00

2.for "bx plugin list" i got the following response

Plugin Name                              Version
IBM_Containers                         1.0.1058
container-registry                      0.1.215
container-service                       0.1.328

3. No i am not using bash as of know in my windows.

**Comment by archerzz** [comment]
@LalithVignesh Would you please run `kubectl` on console directly? If it's put in PATH, then it should be executable.

**Comment by boyang9527** [comment]
it has been a while without response, so closing.  Feel free to reopen it if there is still issue.
