### ISSUE TITLE
Unable to delete multiple Access Groups with the same name automatically

### ISSUE THREAD

**Issue by jmgalvez** [IBM-Cloud/ibm-cloud-cli-release#94]
Hi,

ibmcloud version **0.16.3**.

We are facing an issue regarding IBM Cloud Access Groups.

IBM Cloud allows creating several AGs with the same name. This is weird, but ok, it is how it is.

As part of our automation based on ibmcloud, we delete AGs quite often. But sometimes, the deletion failed...

_FAILED
The following errors have occurred:
Internal Server Error_

and next time the script is executed (and try to create the AG) we end up with several AGs with the same name.

The things is that we do not have any option to delete AGs by command line with a command line argument. -f only force without asking and -r delete ag members. Both are very useful, however we are missing an additional parameter to delete ALL AGs with the same name.

Let's have a look.. I have created 3 different AGs with the same name _to_be_deleted_

```
user@host> ibmcloud iam access-group-delete to_be_deleted
Multiple access groups found.

Select an access group:
Index   ID                                                   Name            Description   
1       AccessGroupId-30998939-1fe7-4b2e-ab5a-c462f78a0630   to_be_deleted      
2       AccessGroupId-7bce87e8-bb5a-4396-8ac1-ecd188869210   to_be_deleted      
3       AccessGroupId-fbc287f4-c184-475f-a616-17a6a744e267   to_be_deleted      
Enter a number [1..3]:> 
```

Withou any argument, ibmcloud offers a multiple choice question, but there is no way to fully automate this. Error code is 1, which is the same as a normal error, so there is no way to make something in our bash script in order to filter this. A different error code, such as 2, might help here as well.

Could you please introduce an additional parameter to force deletion of ALL AGs based on the same name? 

As always, we would really appreciate this!!.

Thank you very much in advance.

**Comment by archerzz** [comment]
@jmgalvez If we allow the first argument to be either name or ID (e.g. from `GROUP_NAME` to `(GROUP_NAME | GROUP_ID)`, does it help? You can iterate all groups with the same name and delete them one by one.
To be honest, it's really rare that multiple resources with the same name are created and then they are deleted altogether. Normally it's quite common that users create multiple resources with the same name (probably by mistake), and then they want to delete one of them.

**Comment by jmgalvez** [comment]
@archerzz Thanks for the quick response. 

I do not actually understand your point. We already have this option, having the first argument as the AG name.  Deleting one by one is possible manually (saying 'yes' with the keyboard), but not automatically.

If the -f option really deleted all them without confirmation, it would be perfect for us, but this is not the case, currently the -f option is not valid if you have multiple AGs. Although the error code is 1, the same as other errors, such as 'internal error'.

In the other hand, your proposal would be valid if we receive a different error code from ibmcloud to know that we are deleting only 1 AG or a multiple AG, so we can iterate several times. Please take in consideration that we do not know in advance if we are processing a single AG or a multiple AG, the automation tool processes all users accounts every night. And if we found a multiple AG is because something weird happened on IBM as exposed previously in my first comment. We ended up with an unexpected situation with multiple AG.

In my opinion, adding a new -a option to force deletion of the AG without confirmation regardless if the AG is single or multiple, then it might be a possible solution.

A valid workaround would be modifying the exit error code to 2 or 3 or whatever, to indicate that you are trying to delete a multiple AG, so you need to iterate one by one. But obviously, we would need a modification that allow us without confirmation, as you suggested, or this is what I understood.

**Comment by archerzz** [comment]
@jmgalvez thanks for detailed explanation. Previously I was thinking if you know in advance about ag, then we can provide a delete by ID option (ID is unique) so that you can delete them one by one.

`-a` makes sense. We'll add it in next release.

**Comment by jmgalvez** [comment]
@archerzz That would be great !!

 Thank you very much.

**Comment by jmgalvez** [comment]
@archerzz Do you have any update for this? We have been looking for this feature in the released versions since last update on July, but unable to find out it.

**Comment by YouHang** [comment]
@jmgalvez this feature will be added in the 0.19.0 which will be released in Sep 20.

**Comment by jmgalvez** [comment]
@YouHang Thanks. I already downloaded the new 0.19.0 and performed a quick check. It worked fine for me with 3 AGs with the same name and I was able to delete all of them with the -a option. 

Thank you again. Very appreciated!!.
