### ISSUE TITLE
Property getter with `--apihost` argument modifies configuration

### ISSUE THREAD

**Issue by joe4dev** [IBM-Cloud/ibm-cloud-cli-release#95]
`whisk CLI version	2019-05-30T22:04:28+00:00`

The property getter `ibmcloud fn property get --apihost` actually changes the whisk API host property.
Example changing to an empty string (because I intend to query apihost and the space between the raw output flag is interpreted as empty string):
![Screenshot 2019-07-12 at 12 17 00](https://user-images.githubusercontent.com/8161292/61121250-0a3c7380-a49f-11e9-8bef-b4f4700ec259.png)
Example changing to arbitrary values:
![Screenshot 2019-07-12 at 12 24 10](https://user-images.githubusercontent.com/8161292/61121645-01986d00-a4a0-11e9-80c6-cae28714414b.png)

This behavior is extremely confusing and unexpected.
Probably related to https://github.com/apache/incubator-openwhisk-cli/issues/435
and also to https://github.com/apache/incubator-openwhisk-cli/commit/23de5a312c5d2332cb5ebd87c90c09da24db1938

Notice that the same buggy behavior does not happen in the latest `76203e8` open source version of `wsk`:
![Screenshot 2019-07-12 at 12 42 26](https://user-images.githubusercontent.com/8161292/61122648-9e5c0a00-a4a2-11e9-8b42-bb008aa5cd7c.png)

**Comment by mdeuser** [comment]
i opened an issue against the functions plugin for this issue
https://github.ibm.com/BlueMix-Fabric/bluemix-openwhisk-cli/issues/360

**Comment by steven0711dong** [comment]
https://github.ibm.com/BlueMix-Fabric/bluemix-openwhisk-cli/pull/401

**Comment by steven0711dong** [comment]
@joe4dev This issue should be fixed now but I cannot close this issue :)

**Comment by joe4dev** [comment]
I can test it when 1.0.35 is released.
Currently, `0.19.0` is the latest version: https://github.com/IBM-Cloud/ibm-cloud-cli-release/releases

**Comment by steven0711dong** [comment]
0.19.0 is for ibm cloud cli. 
 
I was talking about this: 
https://cloud.ibm.com/docs/openwhisk?topic=cloud-functions-cli_versions
Current we are at 1.0.34 and 1.0.35 is coming in 1-2 days. 
 
Simple do this to upgrade to 1.0.34: 
bx plugin repo-plugin cloud-functions
bx plugin install cloud-functions
 
----- Original message -----From: Joel Scheuner <notifications@github.com>To: IBM-Cloud/ibm-cloud-cli-release <ibm-cloud-cli-release@noreply.github.com>Cc: steven0711dong <steven.dong@ibm.com>, Comment <comment@noreply.github.com>Subject: [EXTERNAL] Re: [IBM-Cloud/ibm-cloud-cli-release] Property getter with `--apihost` argument modifies configuration (#95)Date: Tue, Oct 8, 2019 4:41 AM 
I can test it when 1.0.35 is released.Currently, 0.19.0 is the latest version: https://github.com/IBM-Cloud/ibm-cloud-cli-release/releases

**Comment by joe4dev** [comment]
I can confirm that this issue is fixed now in `cloud-functions/wsk/functions/fn   1.0.35` (via ` bx plugin list`). Thanks. Closing this issue.

PS: The [docs](https://cloud.ibm.com/docs/openwhisk?topic=cloud-functions-cli_versions) are not yet updated for `1.0.35`.

**Comment by steven0711dong** [comment]
@joe4dev https://cloud.ibm.com/docs/openwhisk?topic=cloud-functions-cli_versions
